contextSensitive := false
#Include ..\..\..\..\Engine - Keyboard.ahk
InitScript:
global maxMaps := 3
return

Label_e_down:
HKPre()
ActionKey_up_Down("Key_e")
HKPost("Key_e")
return
Label_e_up:
HKUpPre()
ActionKey_up_Up("Key_e")
HKUpPost("Key_e")
return

Label_d_down:
HKPre()
ActionKey_down_Down("Key_d")
HKPost("Key_d")
return
Label_d_up:
HKUpPre()
ActionKey_down_Up("Key_d")
HKUpPost("Key_d")
return

Label_s_down:
HKPre()
ActionKey_left_Down("Key_s")
HKPost("Key_s")
return
Label_s_up:
HKUpPre()
ActionKey_left_Up("Key_s")
HKUpPost("Key_s")
return

Label_f_down:
HKPre()
ActionKey_right_Down("Key_f")
HKPost("Key_f")
return
Label_f_up:
HKUpPre()
ActionKey_right_Up("Key_f")
HKUpPost("Key_f")
return

Label_escape_down:
HKPre()
ActionKey_escape_Down("Key_escape")
HKPost("Key_escape")
return
Label_escape_up:
HKUpPre()
ActionKey_escape_Up("Key_escape")
HKUpPost("Key_escape")
return

Label_scrolllock_down:
HKPre()
ActionKey_scrolllock_Down("Key_scrolllock")
HKPost("Key_scrolllock")
return
Label_scrolllock_up:
HKUpPre()
ActionKey_scrolllock_Up("Key_scrolllock")
HKUpPost("Key_scrolllock")
return

Label_space_down:
HKPre()
ActionKey_space_Down("Key_space")
HKPost("Key_space")
return
Label_space_up:
HKUpPre()
ActionKey_space_Up("Key_space")
HKUpPost("Key_space")
return

Label_tab_down:
MKPre()
SwitchKeymap(2)
MKPost()
return
Label_tab_up:
MKUpPre()
SwitchKeymap(1)
MKUpPost()
return

Label_w_down:
HKPre()
ActionKey_f_Down("Key_w")
HKPost("Key_w")
return
Label_w_up:
HKUpPre()
ActionKey_f_Up("Key_w")
HKUpPost("Key_w")
return

Label_r_down:
HKPre()
ActionKey_e_Down("Key_r")
HKPost("Key_r")
return
Label_r_up:
HKUpPre()
ActionKey_e_Up("Key_r")
HKUpPost("Key_r")
return

Label_g_down:
HKPre()
ActionKey_h_Down("Key_g")
HKPost("Key_g")
return
Label_g_up:
HKUpPre()
ActionKey_h_Up("Key_g")
HKUpPost("Key_g")
return

Label_lshift_down:
MKPre()
SwitchKeymap(3)
MKPost()
return
Label_lshift_up:
MKUpPre()
SwitchKeymap(1)
MKUpPost()
return

Label_2_down:
HKPre()
ActionKey_lctrl_Down("Key_2")
HKPost("Key_2")
return
Label_2_up:
HKUpPre()
ActionKey_lctrl_Up("Key_2")
HKUpPost("Key_2")
return

Label_3_down:
HKPre()
ActionKey_lalt_Down("Key_3")
HKPost("Key_3")
return
Label_3_up:
HKUpPre()
ActionKey_lalt_Up("Key_3")
HKUpPost("Key_3")
return

Label_4_down:
HKPre()
ActionKey_lshift_Down("Key_4")
HKPost("Key_4")
return
Label_4_up:
HKUpPre()
ActionKey_lshift_Up("Key_4")
HKUpPost("Key_4")
return

LabelMap2_q_down:
HKPre()
ActionKey_f1_Down("Key_q")
HKPost("Key_q")
return
LabelMap2_q_up:
HKUpPre()
ActionKey_f1_Up("Key_q")
HKUpPost("Key_q")
return

LabelMap2_w_down:
HKPre()
ActionKey_f2_Down("Key_w")
HKPost("Key_w")
return
LabelMap2_w_up:
HKUpPre()
ActionKey_f2_Up("Key_w")
HKUpPost("Key_w")
return

LabelMap2_e_down:
HKPre()
ActionKey_f3_Down("Key_e")
HKPost("Key_e")
return
LabelMap2_e_up:
HKUpPre()
ActionKey_f3_Up("Key_e")
HKUpPost("Key_e")
return

LabelMap2_r_down:
HKPre()
ActionKey_f4_Down("Key_r")
HKPost("Key_r")
return
LabelMap2_r_up:
HKUpPre()
ActionKey_f4_Up("Key_r")
HKUpPost("Key_r")
return

LabelMap2_t_down:
HKPre()
ActionKey_f5_Down("Key_t")
HKPost("Key_t")
return
LabelMap2_t_up:
HKUpPre()
ActionKey_f5_Up("Key_t")
HKUpPost("Key_t")
return

LabelMap2_a_down:
HKPre()
ActionKey_f6_Down("Key_a")
HKPost("Key_a")
return
LabelMap2_a_up:
HKUpPre()
ActionKey_f6_Up("Key_a")
HKUpPost("Key_a")
return

LabelMap2_s_down:
HKPre()
ActionKey_f7_Down("Key_s")
HKPost("Key_s")
return
LabelMap2_s_up:
HKUpPre()
ActionKey_f7_Up("Key_s")
HKUpPost("Key_s")
return

LabelMap2_d_down:
HKPre()
ActionKey_f8_Down("Key_d")
HKPost("Key_d")
return
LabelMap2_d_up:
HKUpPre()
ActionKey_f8_Up("Key_d")
HKUpPost("Key_d")
return

LabelMap2_f_down:
HKPre()
ActionKey_f9_Down("Key_f")
HKPost("Key_f")
return
LabelMap2_f_up:
HKUpPre()
ActionKey_f9_Up("Key_f")
HKUpPost("Key_f")
return

LabelMap2_g_down:
HKPre()
ActionKey_f10_Down("Key_g")
HKPost("Key_g")
return
LabelMap2_g_up:
HKUpPre()
ActionKey_f10_Up("Key_g")
HKUpPost("Key_g")
return

LabelMap2_1_down:
HKPre()
ActionKey_f11_Down("Key_1")
HKPost("Key_1")
return
LabelMap2_1_up:
HKUpPre()
ActionKey_f11_Up("Key_1")
HKUpPost("Key_1")
return

LabelMap2_2_down:
HKPre()
ActionKey_f12_Down("Key_2")
HKPost("Key_2")
return
LabelMap2_2_up:
HKUpPre()
ActionKey_f12_Up("Key_2")
HKUpPost("Key_2")
return

LabelMap3_r_down:
HKPre()
ActionKey_r_Down("Key_r")
HKPost("Key_r")
return
LabelMap3_r_up:
HKUpPre()
ActionKey_r_Up("Key_r")
HKUpPost("Key_r")
return

LabelMap3_e_down:
HKPre()
ActionKey_lalt_Down("Key_e")
ActionKey_r_Down("Key_e")
HKPost("Key_e")
return
LabelMap3_e_up:
HKUpPre()
ActionKey_r_Up("Key_e")
ActionKey_lalt_Up("Key_e")
HKUpPost("Key_e")
return

LabelMap3_w_down:
HKPre()
ActionKey_lshift_Down("Key_w")
ActionKey_r_Down("Key_w")
HKPost("Key_w")
return
LabelMap3_w_up:
HKUpPre()
ActionKey_r_Up("Key_w")
ActionKey_lshift_Up("Key_w")
HKUpPost("Key_w")
return

LabelMap3_s_down:
HKPre()
ActionKey_i_Down("Key_s")
HKPost("Key_s")
return
LabelMap3_s_up:
HKUpPre()
ActionKey_i_Up("Key_s")
HKUpPost("Key_s")
return

LabelMap3_d_down:
HKPre()
ActionKey_t_Down("Key_d")
HKPost("Key_d")
return
LabelMap3_d_up:
HKUpPre()
ActionKey_t_Up("Key_d")
HKUpPost("Key_d")
return

LabelMap3_f_down:
HKPre()
ActionKey_m_Down("Key_f")
HKPost("Key_f")
return
LabelMap3_f_up:
HKUpPre()
ActionKey_m_Up("Key_f")
HKUpPost("Key_f")
return

LabelMap3_g_down:
HKPre()
ActionKey_q_Down("Key_g")
HKPost("Key_g")
return
LabelMap3_g_up:
HKUpPre()
ActionKey_q_Up("Key_g")
HKUpPost("Key_g")
return

LabelMap3_c_down:
HKPre()
ActionKey_lshift_Down("Key_c")
ActionKey_w_Down("Key_c")
HKPost("Key_c")
return
LabelMap3_c_up:
HKUpPre()
ActionKey_w_Up("Key_c")
ActionKey_lshift_Up("Key_c")
HKUpPost("Key_c")
return

LabelMap3_space_down:
HKPre()
ActionKey_lshift_Down("Key_space")
ActionKey_enter_Down("Key_space")
HKPost("Key_space")
return
LabelMap3_space_up:
HKUpPre()
ActionKey_enter_Up("Key_space")
ActionKey_lshift_Up("Key_space")
HKUpPost("Key_space")
return

LabelMap3_3_down:
HKPre()
ActionKey_b_Down("Key_3")
HKPost("Key_3")
return
LabelMap3_3_up:
HKUpPre()
ActionKey_b_Up("Key_3")
HKUpPost("Key_3")
return

LabelMap3_a_down:
HKPre()
ActionKey_h_Down("Key_a")
HKPost("Key_a")
return
LabelMap3_a_up:
HKUpPre()
ActionKey_h_Up("Key_a")
HKUpPost("Key_a")
return

LabelMap3_z_down:
HKPre()
ActionKey_lshift_Down("Key_z")
ActionKey_p_Down("Key_z")
HKPost("Key_z")
return
LabelMap3_z_up:
HKUpPre()
ActionKey_p_Up("Key_z")
ActionKey_lshift_Up("Key_z")
HKUpPost("Key_z")
return

