contextSensitive := false
#Include ..\..\..\..\Engine - Keyboard.ahk
InitScript:
global maxMaps := 8
return

Label_up_down:
HKPre()
ActionKey_w_Down("Key_up")
HKPost("Key_up")
return
Label_up_up:
HKUpPre()
ActionKey_w_Up("Key_up")
HKUpPost("Key_up")
return

Label_down_down:
HKPre()
ActionKey_s_Down("Key_down")
HKPost("Key_down")
return
Label_down_up:
HKUpPre()
ActionKey_s_Up("Key_down")
HKUpPost("Key_down")
return

Label_left_down:
HKPre()
ActionKey_a_Down("Key_left")
HKPost("Key_left")
return
Label_left_up:
HKUpPre()
ActionKey_a_Up("Key_left")
HKUpPost("Key_left")
return

Label_right_down:
HKPre()
ActionKey_d_Down("Key_right")
HKPost("Key_right")
return
Label_right_up:
HKUpPre()
ActionKey_d_Up("Key_right")
HKUpPost("Key_right")
return

Label_d_down:
HKPre()
ActionKey_space_Down("Key_d")
HKPost("Key_d")
return
Label_d_up:
HKUpPre()
ActionKey_space_Up("Key_d")
HKUpPost("Key_d")
return

Label_c_down:
HKPre()
ActionKey_numpad0_Down("Key_c")
HKPost("Key_c")
return
Label_c_up:
HKUpPre()
ActionKey_numpad0_Up("Key_c")
HKUpPost("Key_c")
return

Label_a_down:
HKPre()
ActionKey_1_Down("Key_a")
HKPost("Key_a")
return
Label_a_up:
HKUpPre()
ActionKey_1_Up("Key_a")
HKUpPost("Key_a")
return

Label_s_down:
HKPre()
ActionKey_2_Down("Key_s")
HKPost("Key_s")
return
Label_s_up:
HKUpPre()
ActionKey_2_Up("Key_s")
HKUpPost("Key_s")
return

Label_f_down:
HKPre()
ActionKey_3_Down("Key_f")
HKPost("Key_f")
return
Label_f_up:
HKUpPre()
ActionKey_3_Up("Key_f")
HKUpPost("Key_f")
return

Label_g_down:
HKPre()
ActionKey_4_Down("Key_g")
HKPost("Key_g")
return
Label_g_up:
HKUpPre()
ActionKey_4_Up("Key_g")
HKUpPost("Key_g")
return

Label_z_down:
HKPre()
ActionKey_5_Down("Key_z")
HKPost("Key_z")
return
Label_z_up:
HKUpPre()
ActionKey_5_Up("Key_z")
HKUpPost("Key_z")
return

Label_x_down:
HKPre()
ActionKey_6_Down("Key_x")
HKPost("Key_x")
return
Label_x_up:
HKUpPre()
ActionKey_6_Up("Key_x")
HKUpPost("Key_x")
return

Label_v_down:
HKPre()
ActionKey_7_Down("Key_v")
HKPost("Key_v")
return
Label_v_up:
HKUpPre()
ActionKey_7_Up("Key_v")
HKUpPost("Key_v")
return

Label_b_down:
HKPre()
ActionKey_8_Down("Key_b")
HKPost("Key_b")
return
Label_b_up:
HKUpPre()
ActionKey_8_Up("Key_b")
HKUpPost("Key_b")
return

Label_q_down:
HKPre()
ActionKey_9_Down("Key_q")
HKPost("Key_q")
return
Label_q_up:
HKUpPre()
ActionKey_9_Up("Key_q")
HKUpPost("Key_q")
return

Label_w_down:
HKPre()
ActionKey_0_Down("Key_w")
HKPost("Key_w")
return
Label_w_up:
HKUpPre()
ActionKey_0_Up("Key_w")
HKUpPost("Key_w")
return

Label_8_down:
MKPre()
SwitchKeymap(2)
MKPost()
return
Label_8_up:
MKUpPre()
SwitchKeymap(1)
MKUpPost()
return

Label_i_down:
MKPre()
SwitchKeymap(3)
MKPost()
return
Label_i_up:
MKUpPre()
SwitchKeymap(1)
MKUpPost()
return

Label_k_down:
MKPre()
SwitchKeymap(4)
MKPost()
return
Label_k_up:
MKUpPre()
SwitchKeymap(1)
MKUpPost()
return

Label_9_down:
MKPre()
SwitchKeymap(5)
MKPost()
return
Label_9_up:
MKUpPre()
SwitchKeymap(1)
MKUpPost()
return

Label_o_down:
MKPre()
SwitchKeymap(6)
MKPost()
return
Label_o_up:
MKUpPre()
SwitchKeymap(1)
MKUpPost()
return

Label_0_down:
MKPre()
SwitchKeymap(7)
MKPost()
return
Label_0_up:
MKUpPre()
SwitchKeymap(1)
MKUpPost()
return

Label_p_down:
MKPre()
SwitchKeymap(8)
MKPost()
return
Label_p_up:
MKUpPre()
SwitchKeymap(1)
MKUpPost()
return

Label_5_down:
HKPre()
ActionKey_sc029_Down("Key_5")
HKPost("Key_5")
return
Label_5_up:
HKUpPre()
ActionKey_sc029_Up("Key_5")
HKUpPost("Key_5")
return

Label_r_down:
HKPre()
ActionKey_vkbd_Down("Key_r")
HKPost("Key_r")
return
Label_r_up:
HKUpPre()
ActionKey_vkbd_Up("Key_r")
HKUpPost("Key_r")
return

Label_t_down:
HKPre()
ActionKey_vkbb_Down("Key_t")
HKPost("Key_t")
return
Label_t_up:
HKUpPre()
ActionKey_vkbb_Up("Key_t")
HKUpPost("Key_t")
return

Label_e_down:
HKPre()
ActionKey_vkdd_Down("Key_e")
HKPost("Key_e")
return
Label_e_up:
HKUpPre()
ActionKey_vkdd_Up("Key_e")
HKUpPost("Key_e")
return

Label_escape_down:
HKPre()
ActionKey_escape_Down("Key_escape")
HKPost("Key_escape")
return
Label_escape_up:
HKUpPre()
ActionKey_escape_Up("Key_escape")
HKUpPost("Key_escape")
return

Label_2_down:
HKPre()
ActionKey_lctrl_Down("Key_2")
HKPost("Key_2")
return
Label_2_up:
HKUpPre()
ActionKey_lctrl_Up("Key_2")
HKUpPost("Key_2")
return

Label_3_down:
HKPre()
ActionKey_lalt_Down("Key_3")
HKPost("Key_3")
return
Label_3_up:
HKUpPre()
ActionKey_lalt_Up("Key_3")
HKUpPost("Key_3")
return

Label_4_down:
HKPre()
ActionKey_lshift_Down("Key_4")
HKPost("Key_4")
return
Label_4_up:
HKUpPre()
ActionKey_lshift_Up("Key_4")
HKUpPost("Key_4")
return

Label_scrolllock_down:
HKPre()
ActionKey_scrolllock_Down("Key_scrolllock")
HKPost("Key_scrolllock")
return
Label_scrolllock_up:
HKUpPre()
ActionKey_scrolllock_Up("Key_scrolllock")
HKUpPost("Key_scrolllock")
return

LabelMap2_a_down:
HKPre()
ActionKey_lctrl_Down("Key_a")
ActionKey_1_Down("Key_a")
HKPost("Key_a")
return
LabelMap2_a_up:
HKUpPre()
ActionKey_1_Up("Key_a")
ActionKey_lctrl_Up("Key_a")
HKUpPost("Key_a")
return

LabelMap2_s_down:
HKPre()
ActionKey_lctrl_Down("Key_s")
ActionKey_2_Down("Key_s")
HKPost("Key_s")
return
LabelMap2_s_up:
HKUpPre()
ActionKey_2_Up("Key_s")
ActionKey_lctrl_Up("Key_s")
HKUpPost("Key_s")
return

LabelMap2_f_down:
HKPre()
ActionKey_lctrl_Down("Key_f")
ActionKey_3_Down("Key_f")
HKPost("Key_f")
return
LabelMap2_f_up:
HKUpPre()
ActionKey_3_Up("Key_f")
ActionKey_lctrl_Up("Key_f")
HKUpPost("Key_f")
return

LabelMap2_g_down:
HKPre()
ActionKey_lctrl_Down("Key_g")
ActionKey_4_Down("Key_g")
HKPost("Key_g")
return
LabelMap2_g_up:
HKUpPre()
ActionKey_4_Up("Key_g")
ActionKey_lctrl_Up("Key_g")
HKUpPost("Key_g")
return

LabelMap2_z_down:
HKPre()
ActionKey_lctrl_Down("Key_z")
ActionKey_5_Down("Key_z")
HKPost("Key_z")
return
LabelMap2_z_up:
HKUpPre()
ActionKey_5_Up("Key_z")
ActionKey_lctrl_Up("Key_z")
HKUpPost("Key_z")
return

LabelMap2_x_down:
HKPre()
ActionKey_lctrl_Down("Key_x")
ActionKey_6_Down("Key_x")
HKPost("Key_x")
return
LabelMap2_x_up:
HKUpPre()
ActionKey_6_Up("Key_x")
ActionKey_lctrl_Up("Key_x")
HKUpPost("Key_x")
return

LabelMap2_v_down:
HKPre()
ActionKey_lctrl_Down("Key_v")
ActionKey_7_Down("Key_v")
HKPost("Key_v")
return
LabelMap2_v_up:
HKUpPre()
ActionKey_7_Up("Key_v")
ActionKey_lctrl_Up("Key_v")
HKUpPost("Key_v")
return

LabelMap2_b_down:
HKPre()
ActionKey_lctrl_Down("Key_b")
ActionKey_8_Down("Key_b")
HKPost("Key_b")
return
LabelMap2_b_up:
HKUpPre()
ActionKey_8_Up("Key_b")
ActionKey_lctrl_Up("Key_b")
HKUpPost("Key_b")
return

LabelMap2_q_down:
HKPre()
ActionKey_lctrl_Down("Key_q")
ActionKey_9_Down("Key_q")
HKPost("Key_q")
return
LabelMap2_q_up:
HKUpPre()
ActionKey_9_Up("Key_q")
ActionKey_lctrl_Up("Key_q")
HKUpPost("Key_q")
return

LabelMap2_w_down:
HKPre()
ActionKey_lctrl_Down("Key_w")
ActionKey_0_Down("Key_w")
HKPost("Key_w")
return
LabelMap2_w_up:
HKUpPre()
ActionKey_0_Up("Key_w")
ActionKey_lctrl_Up("Key_w")
HKUpPost("Key_w")
return

LabelMap2_4_down:
HKPre()
ActionKey_vkbc_Down("Key_4")
HKPost("Key_4")
return
LabelMap2_4_up:
HKUpPre()
ActionKey_vkbc_Up("Key_4")
HKUpPost("Key_4")
return

LabelMap2_3_down:
HKPre()
ActionKey_vkdb_Down("Key_3")
HKPost("Key_3")
return
LabelMap2_3_up:
HKUpPre()
ActionKey_vkdb_Up("Key_3")
HKUpPost("Key_3")
return

LabelMap2_2_down:
HKPre()
ActionKey_vkbe_Down("Key_2")
HKPost("Key_2")
return
LabelMap2_2_up:
HKUpPre()
ActionKey_vkbe_Up("Key_2")
HKUpPost("Key_2")
return

LabelMap2_r_down:
HKPre()
ActionKey_lctrl_Down("Key_r")
ActionKey_vkbd_Down("Key_r")
HKPost("Key_r")
return
LabelMap2_r_up:
HKUpPre()
ActionKey_vkbd_Up("Key_r")
ActionKey_lctrl_Up("Key_r")
HKUpPost("Key_r")
return

LabelMap2_t_down:
HKPre()
ActionKey_lctrl_Down("Key_t")
ActionKey_vkbb_Down("Key_t")
HKPost("Key_t")
return
LabelMap2_t_up:
HKUpPre()
ActionKey_vkbb_Up("Key_t")
ActionKey_lctrl_Up("Key_t")
HKUpPost("Key_t")
return

LabelMap3_a_down:
HKPre()
ActionKey_lshift_Down("Key_a")
ActionKey_1_Down("Key_a")
HKPost("Key_a")
return
LabelMap3_a_up:
HKUpPre()
ActionKey_1_Up("Key_a")
ActionKey_lshift_Up("Key_a")
HKUpPost("Key_a")
return

LabelMap3_s_down:
HKPre()
ActionKey_lshift_Down("Key_s")
ActionKey_2_Down("Key_s")
HKPost("Key_s")
return
LabelMap3_s_up:
HKUpPre()
ActionKey_2_Up("Key_s")
ActionKey_lshift_Up("Key_s")
HKUpPost("Key_s")
return

LabelMap3_f_down:
HKPre()
ActionKey_lshift_Down("Key_f")
ActionKey_3_Down("Key_f")
HKPost("Key_f")
return
LabelMap3_f_up:
HKUpPre()
ActionKey_3_Up("Key_f")
ActionKey_lshift_Up("Key_f")
HKUpPost("Key_f")
return

LabelMap3_g_down:
HKPre()
ActionKey_lshift_Down("Key_g")
ActionKey_4_Down("Key_g")
HKPost("Key_g")
return
LabelMap3_g_up:
HKUpPre()
ActionKey_4_Up("Key_g")
ActionKey_lshift_Up("Key_g")
HKUpPost("Key_g")
return

LabelMap3_z_down:
HKPre()
ActionKey_lshift_Down("Key_z")
ActionKey_5_Down("Key_z")
HKPost("Key_z")
return
LabelMap3_z_up:
HKUpPre()
ActionKey_5_Up("Key_z")
ActionKey_lshift_Up("Key_z")
HKUpPost("Key_z")
return

LabelMap3_x_down:
HKPre()
ActionKey_lshift_Down("Key_x")
ActionKey_6_Down("Key_x")
HKPost("Key_x")
return
LabelMap3_x_up:
HKUpPre()
ActionKey_6_Up("Key_x")
ActionKey_lshift_Up("Key_x")
HKUpPost("Key_x")
return

LabelMap3_v_down:
HKPre()
ActionKey_lshift_Down("Key_v")
ActionKey_7_Down("Key_v")
HKPost("Key_v")
return
LabelMap3_v_up:
HKUpPre()
ActionKey_7_Up("Key_v")
ActionKey_lshift_Up("Key_v")
HKUpPost("Key_v")
return

LabelMap3_b_down:
HKPre()
ActionKey_lshift_Down("Key_b")
ActionKey_8_Down("Key_b")
HKPost("Key_b")
return
LabelMap3_b_up:
HKUpPre()
ActionKey_8_Up("Key_b")
ActionKey_lshift_Up("Key_b")
HKUpPost("Key_b")
return

LabelMap3_q_down:
HKPre()
ActionKey_lshift_Down("Key_q")
ActionKey_9_Down("Key_q")
HKPost("Key_q")
return
LabelMap3_q_up:
HKUpPre()
ActionKey_9_Up("Key_q")
ActionKey_lshift_Up("Key_q")
HKUpPost("Key_q")
return

LabelMap3_w_down:
HKPre()
ActionKey_lshift_Down("Key_w")
ActionKey_0_Down("Key_w")
HKPost("Key_w")
return
LabelMap3_w_up:
HKUpPre()
ActionKey_0_Up("Key_w")
ActionKey_lshift_Up("Key_w")
HKUpPost("Key_w")
return

LabelMap3_r_down:
HKPre()
ActionKey_lshift_Down("Key_r")
ActionKey_vkbd_Down("Key_r")
HKPost("Key_r")
return
LabelMap3_r_up:
HKUpPre()
ActionKey_vkbd_Up("Key_r")
ActionKey_lshift_Up("Key_r")
HKUpPost("Key_r")
return

LabelMap3_t_down:
HKPre()
ActionKey_lshift_Down("Key_t")
ActionKey_vkbb_Down("Key_t")
HKPost("Key_t")
return
LabelMap3_t_up:
HKUpPre()
ActionKey_vkbb_Up("Key_t")
ActionKey_lshift_Up("Key_t")
HKUpPost("Key_t")
return

LabelMap3_2_down:
HKPre()
ActionKey_tab_Down("Key_2")
HKPost("Key_2")
return
LabelMap3_2_up:
HKUpPre()
ActionKey_tab_Up("Key_2")
HKUpPost("Key_2")
return

LabelMap3_3_down:
HKPre()
ActionKey_f_Down("Key_3")
HKPost("Key_3")
return
LabelMap3_3_up:
HKUpPre()
ActionKey_f_Up("Key_3")
HKUpPost("Key_3")
return

LabelMap3_4_down:
HKPre()
ActionKey_t_Down("Key_4")
HKPost("Key_4")
return
LabelMap3_4_up:
HKUpPre()
ActionKey_t_Up("Key_4")
HKUpPost("Key_4")
return

LabelMap4_a_down:
HKPre()
ActionKey_lalt_Down("Key_a")
ActionKey_1_Down("Key_a")
HKPost("Key_a")
return
LabelMap4_a_up:
HKUpPre()
ActionKey_1_Up("Key_a")
ActionKey_lalt_Up("Key_a")
HKUpPost("Key_a")
return

LabelMap4_s_down:
HKPre()
ActionKey_lalt_Down("Key_s")
ActionKey_2_Down("Key_s")
HKPost("Key_s")
return
LabelMap4_s_up:
HKUpPre()
ActionKey_2_Up("Key_s")
ActionKey_lalt_Up("Key_s")
HKUpPost("Key_s")
return

LabelMap4_f_down:
HKPre()
ActionKey_lalt_Down("Key_f")
ActionKey_3_Down("Key_f")
HKPost("Key_f")
return
LabelMap4_f_up:
HKUpPre()
ActionKey_3_Up("Key_f")
ActionKey_lalt_Up("Key_f")
HKUpPost("Key_f")
return

LabelMap4_g_down:
HKPre()
ActionKey_lalt_Down("Key_g")
ActionKey_4_Down("Key_g")
HKPost("Key_g")
return
LabelMap4_g_up:
HKUpPre()
ActionKey_4_Up("Key_g")
ActionKey_lalt_Up("Key_g")
HKUpPost("Key_g")
return

LabelMap4_z_down:
HKPre()
ActionKey_lalt_Down("Key_z")
ActionKey_5_Down("Key_z")
HKPost("Key_z")
return
LabelMap4_z_up:
HKUpPre()
ActionKey_5_Up("Key_z")
ActionKey_lalt_Up("Key_z")
HKUpPost("Key_z")
return

LabelMap4_x_down:
HKPre()
ActionKey_lalt_Down("Key_x")
ActionKey_6_Down("Key_x")
HKPost("Key_x")
return
LabelMap4_x_up:
HKUpPre()
ActionKey_6_Up("Key_x")
ActionKey_lalt_Up("Key_x")
HKUpPost("Key_x")
return

LabelMap4_v_down:
HKPre()
ActionKey_lalt_Down("Key_v")
ActionKey_7_Down("Key_v")
HKPost("Key_v")
return
LabelMap4_v_up:
HKUpPre()
ActionKey_7_Up("Key_v")
ActionKey_lalt_Up("Key_v")
HKUpPost("Key_v")
return

LabelMap4_b_down:
HKPre()
ActionKey_lalt_Down("Key_b")
ActionKey_8_Down("Key_b")
HKPost("Key_b")
return
LabelMap4_b_up:
HKUpPre()
ActionKey_8_Up("Key_b")
ActionKey_lalt_Up("Key_b")
HKUpPost("Key_b")
return

LabelMap4_q_down:
HKPre()
ActionKey_lalt_Down("Key_q")
ActionKey_9_Down("Key_q")
HKPost("Key_q")
return
LabelMap4_q_up:
HKUpPre()
ActionKey_9_Up("Key_q")
ActionKey_lalt_Up("Key_q")
HKUpPost("Key_q")
return

LabelMap4_w_down:
HKPre()
ActionKey_lalt_Down("Key_w")
ActionKey_0_Down("Key_w")
HKPost("Key_w")
return
LabelMap4_w_up:
HKUpPre()
ActionKey_0_Up("Key_w")
ActionKey_lalt_Up("Key_w")
HKUpPost("Key_w")
return

LabelMap4_r_down:
HKPre()
ActionKey_lalt_Down("Key_r")
ActionKey_vkbd_Down("Key_r")
HKPost("Key_r")
return
LabelMap4_r_up:
HKUpPre()
ActionKey_vkbd_Up("Key_r")
ActionKey_lalt_Up("Key_r")
HKUpPost("Key_r")
return

LabelMap4_t_down:
HKPre()
ActionKey_lalt_Down("Key_t")
ActionKey_vkbb_Down("Key_t")
HKPost("Key_t")
return
LabelMap4_t_up:
HKUpPre()
ActionKey_vkbb_Up("Key_t")
ActionKey_lalt_Up("Key_t")
HKUpPost("Key_t")
return

LabelMap5_d_down:
HKPre()
ActionKey_c_Down("Key_d")
HKPost("Key_d")
return
LabelMap5_d_up:
HKUpPre()
ActionKey_c_Up("Key_d")
HKUpPost("Key_d")
return

LabelMap5_f_down:
HKPre()
ActionKey_b_Down("Key_f")
HKPost("Key_f")
return
LabelMap5_f_up:
HKUpPre()
ActionKey_b_Up("Key_f")
HKUpPost("Key_f")
return

LabelMap5_s_down:
HKPre()
ActionKey_n_Down("Key_s")
HKPost("Key_s")
return
LabelMap5_s_up:
HKUpPre()
ActionKey_n_Up("Key_s")
HKUpPost("Key_s")
return

LabelMap5_a_down:
HKPre()
ActionKey_p_Down("Key_a")
HKPost("Key_a")
return
LabelMap5_a_up:
HKUpPre()
ActionKey_p_Up("Key_a")
HKUpPost("Key_a")
return

LabelMap5_g_down:
HKPre()
ActionKey_l_Down("Key_g")
HKPost("Key_g")
return
LabelMap5_g_up:
HKUpPre()
ActionKey_l_Up("Key_g")
HKUpPost("Key_g")
return

LabelMap5_c_down:
HKPre()
ActionKey_m_Down("Key_c")
HKPost("Key_c")
return
LabelMap5_c_up:
HKUpPre()
ActionKey_m_Up("Key_c")
HKUpPost("Key_c")
return

LabelMap5_z_down:
HKPre()
ActionKey_y_Down("Key_z")
HKPost("Key_z")
return
LabelMap5_z_up:
HKUpPre()
ActionKey_y_Up("Key_z")
HKUpPost("Key_z")
return

LabelMap5_x_down:
HKPre()
ActionKey_lshift_Down("Key_x")
ActionKey_j_Down("Key_x")
HKPost("Key_x")
return
LabelMap5_x_up:
HKUpPre()
ActionKey_j_Up("Key_x")
ActionKey_lshift_Up("Key_x")
HKUpPost("Key_x")
return

LabelMap5_v_down:
HKPre()
ActionKey_o_Down("Key_v")
HKPost("Key_v")
return
LabelMap5_v_up:
HKUpPre()
ActionKey_o_Up("Key_v")
HKUpPost("Key_v")
return

LabelMap5_b_down:
HKPre()
ActionKey_j_Down("Key_b")
HKPost("Key_b")
return
LabelMap5_b_up:
HKUpPre()
ActionKey_j_Up("Key_b")
HKUpPost("Key_b")
return

LabelMap5_e_down:
HKPre()
ActionKey_i_Down("Key_e")
HKPost("Key_e")
return
LabelMap5_e_up:
HKUpPre()
ActionKey_i_Up("Key_e")
HKUpPost("Key_e")
return

LabelMap5_r_down:
HKPre()
ActionKey_lctrl_Down("Key_r")
ActionKey_g_Down("Key_r")
HKPost("Key_r")
return
LabelMap5_r_up:
HKUpPre()
ActionKey_g_Up("Key_r")
ActionKey_lctrl_Up("Key_r")
HKUpPost("Key_r")
return

LabelMap5_w_down:
HKPre()
ActionKey_lshift_Down("Key_w")
ActionKey_p_Down("Key_w")
HKPost("Key_w")
return
LabelMap5_w_up:
HKUpPre()
ActionKey_p_Up("Key_w")
ActionKey_lshift_Up("Key_w")
HKUpPost("Key_w")
return

LabelMap6_s_down:
HKPre()
ActionKey_lalt_Down("Key_s")
ActionKey_e_Down("Key_s")
HKPost("Key_s")
return
LabelMap6_s_up:
HKUpPre()
ActionKey_e_Up("Key_s")
ActionKey_lalt_Up("Key_s")
HKUpPost("Key_s")
return

LabelMap6_f_down:
HKPre()
ActionKey_lalt_Down("Key_f")
ActionKey_x_Down("Key_f")
HKPost("Key_f")
return
LabelMap6_f_up:
HKUpPre()
ActionKey_x_Up("Key_f")
ActionKey_lalt_Up("Key_f")
HKUpPost("Key_f")
return

LabelMap6_g_down:
HKPre()
ActionKey_lalt_Down("Key_g")
ActionKey_c_Down("Key_g")
HKPost("Key_g")
return
LabelMap6_g_up:
HKUpPre()
ActionKey_c_Up("Key_g")
ActionKey_lalt_Up("Key_g")
HKUpPost("Key_g")
return

LabelMap6_a_down:
HKPre()
ActionKey_lalt_Down("Key_a")
ActionKey_z_Down("Key_a")
HKPost("Key_a")
return
LabelMap6_a_up:
HKUpPre()
ActionKey_z_Up("Key_a")
ActionKey_lalt_Up("Key_a")
HKUpPost("Key_a")
return

LabelMap6_e_down:
HKPre()
ActionKey_lalt_Down("Key_e")
ActionKey_q_Down("Key_e")
HKPost("Key_e")
return
LabelMap6_e_up:
HKUpPre()
ActionKey_q_Up("Key_e")
ActionKey_lalt_Up("Key_e")
HKUpPost("Key_e")
return

LabelMap6_z_down:
HKPre()
ActionKey_lalt_Down("Key_z")
ActionKey_sc029_Down("Key_z")
HKPost("Key_z")
return
LabelMap6_z_up:
HKUpPre()
ActionKey_sc029_Up("Key_z")
ActionKey_lalt_Up("Key_z")
HKUpPost("Key_z")
return

LabelMap6_r_down:
HKPre()
ActionKey_lalt_Down("Key_r")
ActionKey_f_Down("Key_r")
HKPost("Key_r")
return
LabelMap6_r_up:
HKUpPre()
ActionKey_f_Up("Key_r")
ActionKey_lalt_Up("Key_r")
HKUpPost("Key_r")
return

LabelMap6_w_down:
HKPre()
ActionKey_lalt_Down("Key_w")
ActionKey_r_Down("Key_w")
HKPost("Key_w")
return
LabelMap6_w_up:
HKUpPre()
ActionKey_r_Up("Key_w")
ActionKey_lalt_Up("Key_w")
HKUpPost("Key_w")
return

LabelMap6_x_down:
HKPre()
ActionKey_lalt_Down("Key_x")
ActionKey_v_Down("Key_x")
HKPost("Key_x")
return
LabelMap6_x_up:
HKUpPre()
ActionKey_v_Up("Key_x")
ActionKey_lalt_Up("Key_x")
HKUpPost("Key_x")
return

LabelMap6_3_down:
HKPre()
ActionKey_lctrl_Down("Key_3")
ActionKey_lalt_Down("Key_3")
ActionKey_e_Down("Key_3")
HKPost("Key_3")
return
LabelMap6_3_up:
HKUpPre()
ActionKey_e_Up("Key_3")
ActionKey_lctrl_Up("Key_3")
ActionKey_lalt_Up("Key_3")
HKUpPost("Key_3")
return

LabelMap7_s_down:
HKPre()
ActionKey_lalt_Down("Key_s")
ActionKey_n_Down("Key_s")
HKPost("Key_s")
return
LabelMap7_s_up:
HKUpPre()
ActionKey_n_Up("Key_s")
ActionKey_lalt_Up("Key_s")
HKUpPost("Key_s")
return

LabelMap7_f_down:
HKPre()
ActionKey_lalt_Down("Key_f")
ActionKey_m_Down("Key_f")
HKPost("Key_f")
return
LabelMap7_f_up:
HKUpPre()
ActionKey_m_Up("Key_f")
ActionKey_lalt_Up("Key_f")
HKUpPost("Key_f")
return

LabelMap7_z_down:
HKPre()
ActionKey_lctrl_Down("Key_z")
ActionKey_lalt_Down("Key_z")
ActionKey_sc029_Down("Key_z")
HKPost("Key_z")
return
LabelMap7_z_up:
HKUpPre()
ActionKey_sc029_Up("Key_z")
ActionKey_lctrl_Up("Key_z")
ActionKey_lalt_Up("Key_z")
HKUpPost("Key_z")
return

LabelMap7_w_down:
HKPre()
ActionKey_lalt_Down("Key_w")
ActionKey_vkdb_Down("Key_w")
HKPost("Key_w")
return
LabelMap7_w_up:
HKUpPre()
ActionKey_vkdb_Up("Key_w")
ActionKey_lalt_Up("Key_w")
HKUpPost("Key_w")
return

LabelMap7_r_down:
HKPre()
ActionKey_lalt_Down("Key_r")
ActionKey_vkdd_Down("Key_r")
HKPost("Key_r")
return
LabelMap7_r_up:
HKUpPre()
ActionKey_vkdd_Up("Key_r")
ActionKey_lalt_Up("Key_r")
HKUpPost("Key_r")
return

LabelMap8_f_down:
HKPre()
ActionKey_z_Down("Key_f")
HKPost("Key_f")
return
LabelMap8_f_up:
HKUpPre()
ActionKey_z_Up("Key_f")
HKUpPost("Key_f")
return

LabelMap8_s_down:
HKPre()
ActionKey_x_Down("Key_s")
HKPost("Key_s")
return
LabelMap8_s_up:
HKUpPre()
ActionKey_x_Up("Key_s")
HKUpPost("Key_s")
return

LabelMap8_z_down:
HKPre()
ActionKey_f2_Down("Key_z")
HKPost("Key_z")
return
LabelMap8_z_up:
HKUpPre()
ActionKey_f2_Up("Key_z")
HKUpPost("Key_z")
return

LabelMap8_x_down:
HKPre()
ActionKey_f3_Down("Key_x")
HKPost("Key_x")
return
LabelMap8_x_up:
HKUpPre()
ActionKey_f3_Up("Key_x")
HKUpPost("Key_x")
return

LabelMap8_v_down:
HKPre()
ActionKey_f4_Down("Key_v")
HKPost("Key_v")
return
LabelMap8_v_up:
HKUpPre()
ActionKey_f4_Up("Key_v")
HKUpPost("Key_v")
return

LabelMap8_b_down:
HKPre()
ActionKey_f5_Down("Key_b")
HKPost("Key_b")
return
LabelMap8_b_up:
HKUpPre()
ActionKey_f5_Up("Key_b")
HKUpPost("Key_b")
return

LabelMap8_4_down:
HKPre()
ActionKey_v_Down("Key_4")
HKPost("Key_4")
return
LabelMap8_4_up:
HKUpPre()
ActionKey_v_Up("Key_4")
HKUpPost("Key_4")
return

