contextSensitive := false
#Include ..\..\..\..\Engine - Keyboard.ahk
InitScript:
global maxMaps := 8
return

Label_e_down:
HKPre()
ActionKey_w_Down("Key_e")
HKPost("Key_e")
return
Label_e_up:
HKUpPre()
ActionKey_w_Up("Key_e")
HKUpPost("Key_e")
return

Label_d_down:
HKPre()
ActionKey_s_Down("Key_d")
HKPost("Key_d")
return
Label_d_up:
HKUpPre()
ActionKey_s_Up("Key_d")
HKUpPost("Key_d")
return

Label_s_down:
HKPre()
ActionKey_a_Down("Key_s")
HKPost("Key_s")
return
Label_s_up:
HKUpPre()
ActionKey_a_Up("Key_s")
HKUpPost("Key_s")
return

Label_f_down:
HKPre()
ActionKey_d_Down("Key_f")
HKPost("Key_f")
return
Label_f_up:
HKUpPre()
ActionKey_d_Up("Key_f")
HKUpPost("Key_f")
return

Label_w_down:
HKPre()
ActionKey_1_Down("Key_w")
HKPost("Key_w")
return
Label_w_up:
HKUpPre()
ActionKey_1_Up("Key_w")
HKUpPost("Key_w")
return

Label_r_down:
HKPre()
ActionKey_2_Down("Key_r")
HKPost("Key_r")
return
Label_r_up:
HKUpPre()
ActionKey_2_Up("Key_r")
HKUpPost("Key_r")
return

Label_t_down:
HKPre()
ActionKey_3_Down("Key_t")
HKPost("Key_t")
return
Label_t_up:
HKUpPre()
ActionKey_3_Up("Key_t")
HKUpPost("Key_t")
return

Label_g_down:
HKPre()
ActionKey_4_Down("Key_g")
HKPost("Key_g")
return
Label_g_up:
HKUpPre()
ActionKey_4_Up("Key_g")
HKUpPost("Key_g")
return

Label_x_down:
HKPre()
ActionKey_5_Down("Key_x")
HKPost("Key_x")
return
Label_x_up:
HKUpPre()
ActionKey_5_Up("Key_x")
HKUpPost("Key_x")
return

Label_c_down:
HKPre()
ActionKey_6_Down("Key_c")
HKPost("Key_c")
return
Label_c_up:
HKUpPre()
ActionKey_6_Up("Key_c")
HKUpPost("Key_c")
return

Label_v_down:
HKPre()
ActionKey_7_Down("Key_v")
HKPost("Key_v")
return
Label_v_up:
HKUpPre()
ActionKey_7_Up("Key_v")
HKUpPost("Key_v")
return

Label_escape_down:
HKPre()
ActionKey_escape_Down("Key_escape")
HKPost("Key_escape")
return
Label_escape_up:
HKUpPre()
ActionKey_escape_Up("Key_escape")
HKUpPost("Key_escape")
return

Label_scrolllock_down:
HKPre()
ActionKey_scrolllock_Down("Key_scrolllock")
HKPost("Key_scrolllock")
return
Label_scrolllock_up:
HKUpPre()
ActionKey_scrolllock_Up("Key_scrolllock")
HKUpPost("Key_scrolllock")
return

Label_space_down:
HKPre()
ActionKey_space_Down("Key_space")
HKPost("Key_space")
return
Label_space_up:
HKUpPre()
ActionKey_space_Up("Key_space")
HKUpPost("Key_space")
return

Label_h_down:
HKPre()
ActionKey_vkdd_Down("Key_h")
HKPost("Key_h")
return
Label_h_up:
HKUpPre()
ActionKey_vkdd_Up("Key_h")
HKUpPost("Key_h")
return

Label_a_down:
MKPre()
SwitchKeymap(2)
MKPost()
return
Label_a_up:
MKUpPre()
SwitchKeymap(1)
MKUpPost()
return

Label_q_down:
MKPre()
SwitchKeymap(3)
MKPost()
return
Label_q_up:
MKUpPre()
SwitchKeymap(1)
MKUpPost()
return

Label_z_down:
MKPre()
SwitchKeymap(4)
MKPost()
return
Label_z_up:
MKUpPre()
SwitchKeymap(1)
MKUpPost()
return

Label_y_down:
HKPre()
ActionKey_vkbb_Down("Key_y")
HKPost("Key_y")
return
Label_y_up:
HKUpPre()
ActionKey_vkbb_Up("Key_y")
HKUpPost("Key_y")
return

Label_lshift_down:
MKPre()
SwitchKeymap(5)
MKPost()
return
Label_lshift_up:
MKUpPre()
SwitchKeymap(1)
MKUpPost()
return

Label_tab_down:
MKPre()
SwitchKeymap(6)
MKPost()
return
Label_tab_up:
MKUpPre()
SwitchKeymap(1)
MKUpPost()
return

Label_lctrl_down:
MKPre()
SwitchKeymap(7)
MKPost()
return
Label_lctrl_up:
MKUpPre()
SwitchKeymap(1)
MKUpPost()
return

Label_b_down:
HKPre()
ActionKey_8_Down("Key_b")
HKPost("Key_b")
return
Label_b_up:
HKUpPre()
ActionKey_8_Up("Key_b")
HKUpPost("Key_b")
return

Label_5_down:
HKPre()
ActionKey_numpad0_Down("Key_5")
HKPost("Key_5")
return
Label_5_up:
HKUpPre()
ActionKey_numpad0_Up("Key_5")
HKUpPost("Key_5")
return

Label_lalt_down:
MKPre()
SwitchKeymap(8)
MKPost()
return
Label_lalt_up:
MKUpPre()
SwitchKeymap(1)
MKUpPost()
return

Label_2_down:
HKPre()
ActionKey_lctrl_Down("Key_2")
HKPost("Key_2")
return
Label_2_up:
HKUpPre()
ActionKey_lctrl_Up("Key_2")
HKUpPost("Key_2")
return

Label_3_down:
HKPre()
ActionKey_lalt_Down("Key_3")
HKPost("Key_3")
return
Label_3_up:
HKUpPre()
ActionKey_lalt_Up("Key_3")
HKUpPost("Key_3")
return

Label_4_down:
HKPre()
ActionKey_lshift_Down("Key_4")
HKPost("Key_4")
return
Label_4_up:
HKUpPre()
ActionKey_lshift_Up("Key_4")
HKUpPost("Key_4")
return

Label_capslock_down:
HKPre()
ActionKey_f13_Down("Key_capslock")
HKPost("Key_capslock")
return
Label_capslock_up:
HKUpPre()
ActionKey_f13_Up("Key_capslock")
HKUpPost("Key_capslock")
return

Label_f13_down:
HKPre()
ActionKey_f13_Down("Key_f13")
HKPost("Key_f13")
return
Label_f13_up:
HKUpPre()
ActionKey_f13_Up("Key_f13")
HKUpPost("Key_f13")
return

Label_sc029_down:
HKPre()
ActionKey_sc029_Down("Key_sc029")
HKPost("Key_sc029")
return
Label_sc029_up:
HKUpPre()
ActionKey_sc029_Up("Key_sc029")
HKUpPost("Key_sc029")
return

LabelMap2_w_down:
HKPre()
ActionKey_lshift_Down("Key_w")
ActionKey_1_Down("Key_w")
HKPost("Key_w")
return
LabelMap2_w_up:
HKUpPre()
ActionKey_1_Up("Key_w")
ActionKey_lshift_Up("Key_w")
HKUpPost("Key_w")
return

LabelMap2_r_down:
HKPre()
ActionKey_lshift_Down("Key_r")
ActionKey_2_Down("Key_r")
HKPost("Key_r")
return
LabelMap2_r_up:
HKUpPre()
ActionKey_2_Up("Key_r")
ActionKey_lshift_Up("Key_r")
HKUpPost("Key_r")
return

LabelMap2_t_down:
HKPre()
ActionKey_lshift_Down("Key_t")
ActionKey_3_Down("Key_t")
HKPost("Key_t")
return
LabelMap2_t_up:
HKUpPre()
ActionKey_3_Up("Key_t")
ActionKey_lshift_Up("Key_t")
HKUpPost("Key_t")
return

LabelMap2_g_down:
HKPre()
ActionKey_lshift_Down("Key_g")
ActionKey_4_Down("Key_g")
HKPost("Key_g")
return
LabelMap2_g_up:
HKUpPre()
ActionKey_4_Up("Key_g")
ActionKey_lshift_Up("Key_g")
HKUpPost("Key_g")
return

LabelMap2_x_down:
HKPre()
ActionKey_lshift_Down("Key_x")
ActionKey_5_Down("Key_x")
HKPost("Key_x")
return
LabelMap2_x_up:
HKUpPre()
ActionKey_5_Up("Key_x")
ActionKey_lshift_Up("Key_x")
HKUpPost("Key_x")
return

LabelMap2_c_down:
HKPre()
ActionKey_lshift_Down("Key_c")
ActionKey_6_Down("Key_c")
HKPost("Key_c")
return
LabelMap2_c_up:
HKUpPre()
ActionKey_6_Up("Key_c")
ActionKey_lshift_Up("Key_c")
HKUpPost("Key_c")
return

LabelMap2_v_down:
HKPre()
ActionKey_lshift_Down("Key_v")
ActionKey_7_Down("Key_v")
HKPost("Key_v")
return
LabelMap2_v_up:
HKUpPre()
ActionKey_7_Up("Key_v")
ActionKey_lshift_Up("Key_v")
HKUpPost("Key_v")
return

LabelMap2_b_down:
HKPre()
ActionKey_lshift_Down("Key_b")
ActionKey_8_Down("Key_b")
HKPost("Key_b")
return
LabelMap2_b_up:
HKUpPre()
ActionKey_8_Up("Key_b")
ActionKey_lshift_Up("Key_b")
HKUpPost("Key_b")
return

LabelMap2_2_down:
HKPre()
ActionKey_tab_Down("Key_2")
HKPost("Key_2")
return
LabelMap2_2_up:
HKUpPre()
ActionKey_tab_Up("Key_2")
HKUpPost("Key_2")
return

LabelMap2_3_down:
HKPre()
ActionKey_f_Down("Key_3")
HKPost("Key_3")
return
LabelMap2_3_up:
HKUpPre()
ActionKey_f_Up("Key_3")
HKUpPost("Key_3")
return

LabelMap2_4_down:
HKPre()
ActionKey_t_Down("Key_4")
HKPost("Key_4")
return
LabelMap2_4_up:
HKUpPre()
ActionKey_t_Up("Key_4")
HKUpPost("Key_4")
return

LabelMap2_y_down:
HKPre()
ActionKey_lshift_Down("Key_y")
ActionKey_vkbb_Down("Key_y")
HKPost("Key_y")
return
LabelMap2_y_up:
HKUpPre()
ActionKey_vkbb_Up("Key_y")
ActionKey_lshift_Up("Key_y")
HKUpPost("Key_y")
return

LabelMap3_w_down:
HKPre()
ActionKey_lctrl_Down("Key_w")
ActionKey_1_Down("Key_w")
HKPost("Key_w")
return
LabelMap3_w_up:
HKUpPre()
ActionKey_1_Up("Key_w")
ActionKey_lctrl_Up("Key_w")
HKUpPost("Key_w")
return

LabelMap3_r_down:
HKPre()
ActionKey_lctrl_Down("Key_r")
ActionKey_2_Down("Key_r")
HKPost("Key_r")
return
LabelMap3_r_up:
HKUpPre()
ActionKey_2_Up("Key_r")
ActionKey_lctrl_Up("Key_r")
HKUpPost("Key_r")
return

LabelMap3_t_down:
HKPre()
ActionKey_lctrl_Down("Key_t")
ActionKey_3_Down("Key_t")
HKPost("Key_t")
return
LabelMap3_t_up:
HKUpPre()
ActionKey_3_Up("Key_t")
ActionKey_lctrl_Up("Key_t")
HKUpPost("Key_t")
return

LabelMap3_g_down:
HKPre()
ActionKey_lctrl_Down("Key_g")
ActionKey_4_Down("Key_g")
HKPost("Key_g")
return
LabelMap3_g_up:
HKUpPre()
ActionKey_4_Up("Key_g")
ActionKey_lctrl_Up("Key_g")
HKUpPost("Key_g")
return

LabelMap3_x_down:
HKPre()
ActionKey_lctrl_Down("Key_x")
ActionKey_5_Down("Key_x")
HKPost("Key_x")
return
LabelMap3_x_up:
HKUpPre()
ActionKey_5_Up("Key_x")
ActionKey_lctrl_Up("Key_x")
HKUpPost("Key_x")
return

LabelMap3_c_down:
HKPre()
ActionKey_lctrl_Down("Key_c")
ActionKey_6_Down("Key_c")
HKPost("Key_c")
return
LabelMap3_c_up:
HKUpPre()
ActionKey_6_Up("Key_c")
ActionKey_lctrl_Up("Key_c")
HKUpPost("Key_c")
return

LabelMap3_v_down:
HKPre()
ActionKey_lctrl_Down("Key_v")
ActionKey_7_Down("Key_v")
HKPost("Key_v")
return
LabelMap3_v_up:
HKUpPre()
ActionKey_7_Up("Key_v")
ActionKey_lctrl_Up("Key_v")
HKUpPost("Key_v")
return

LabelMap3_b_down:
HKPre()
ActionKey_lctrl_Down("Key_b")
ActionKey_8_Down("Key_b")
HKPost("Key_b")
return
LabelMap3_b_up:
HKUpPre()
ActionKey_8_Up("Key_b")
ActionKey_lctrl_Up("Key_b")
HKUpPost("Key_b")
return

LabelMap3_1_down:
HKPre()
ActionKey_f2_Down("Key_1")
HKPost("Key_1")
return
LabelMap3_1_up:
HKUpPre()
ActionKey_f2_Up("Key_1")
HKUpPost("Key_1")
return

LabelMap3_2_down:
HKPre()
ActionKey_f3_Down("Key_2")
HKPost("Key_2")
return
LabelMap3_2_up:
HKUpPre()
ActionKey_f3_Up("Key_2")
HKUpPost("Key_2")
return

LabelMap3_3_down:
HKPre()
ActionKey_f4_Down("Key_3")
HKPost("Key_3")
return
LabelMap3_3_up:
HKUpPre()
ActionKey_f4_Up("Key_3")
HKUpPost("Key_3")
return

LabelMap3_4_down:
HKPre()
ActionKey_f5_Down("Key_4")
HKPost("Key_4")
return
LabelMap3_4_up:
HKUpPre()
ActionKey_f5_Up("Key_4")
HKUpPost("Key_4")
return

LabelMap3_y_down:
HKPre()
ActionKey_lctrl_Down("Key_y")
ActionKey_vkbb_Down("Key_y")
HKPost("Key_y")
return
LabelMap3_y_up:
HKUpPre()
ActionKey_vkbb_Up("Key_y")
ActionKey_lctrl_Up("Key_y")
HKUpPost("Key_y")
return

LabelMap4_w_down:
HKPre()
ActionKey_lalt_Down("Key_w")
ActionKey_1_Down("Key_w")
HKPost("Key_w")
return
LabelMap4_w_up:
HKUpPre()
ActionKey_1_Up("Key_w")
ActionKey_lalt_Up("Key_w")
HKUpPost("Key_w")
return

LabelMap4_r_down:
HKPre()
ActionKey_lalt_Down("Key_r")
ActionKey_2_Down("Key_r")
HKPost("Key_r")
return
LabelMap4_r_up:
HKUpPre()
ActionKey_2_Up("Key_r")
ActionKey_lalt_Up("Key_r")
HKUpPost("Key_r")
return

LabelMap4_t_down:
HKPre()
ActionKey_lalt_Down("Key_t")
ActionKey_3_Down("Key_t")
HKPost("Key_t")
return
LabelMap4_t_up:
HKUpPre()
ActionKey_3_Up("Key_t")
ActionKey_lalt_Up("Key_t")
HKUpPost("Key_t")
return

LabelMap4_g_down:
HKPre()
ActionKey_lalt_Down("Key_g")
ActionKey_4_Down("Key_g")
HKPost("Key_g")
return
LabelMap4_g_up:
HKUpPre()
ActionKey_4_Up("Key_g")
ActionKey_lalt_Up("Key_g")
HKUpPost("Key_g")
return

LabelMap4_x_down:
HKPre()
ActionKey_lalt_Down("Key_x")
ActionKey_5_Down("Key_x")
HKPost("Key_x")
return
LabelMap4_x_up:
HKUpPre()
ActionKey_5_Up("Key_x")
ActionKey_lalt_Up("Key_x")
HKUpPost("Key_x")
return

LabelMap4_c_down:
HKPre()
ActionKey_lalt_Down("Key_c")
ActionKey_6_Down("Key_c")
HKPost("Key_c")
return
LabelMap4_c_up:
HKUpPre()
ActionKey_6_Up("Key_c")
ActionKey_lalt_Up("Key_c")
HKUpPost("Key_c")
return

LabelMap4_v_down:
HKPre()
ActionKey_lalt_Down("Key_v")
ActionKey_7_Down("Key_v")
HKPost("Key_v")
return
LabelMap4_v_up:
HKUpPre()
ActionKey_7_Up("Key_v")
ActionKey_lalt_Up("Key_v")
HKUpPost("Key_v")
return

LabelMap4_b_down:
HKPre()
ActionKey_lalt_Down("Key_b")
ActionKey_8_Down("Key_b")
HKPost("Key_b")
return
LabelMap4_b_up:
HKUpPre()
ActionKey_8_Up("Key_b")
ActionKey_lalt_Up("Key_b")
HKUpPost("Key_b")
return

LabelMap4_y_down:
HKPre()
ActionKey_lalt_Down("Key_y")
ActionKey_vkbb_Down("Key_y")
HKPost("Key_y")
return
LabelMap4_y_up:
HKUpPre()
ActionKey_vkbb_Up("Key_y")
ActionKey_lalt_Up("Key_y")
HKUpPost("Key_y")
return

LabelMap5_e_down:
HKPre()
ActionKey_lalt_Down("Key_e")
ActionKey_e_Down("Key_e")
HKPost("Key_e")
return
LabelMap5_e_up:
HKUpPre()
ActionKey_e_Up("Key_e")
ActionKey_lalt_Up("Key_e")
HKUpPost("Key_e")
return

LabelMap5_s_down:
HKPre()
ActionKey_lalt_Down("Key_s")
ActionKey_z_Down("Key_s")
HKPost("Key_s")
return
LabelMap5_s_up:
HKUpPre()
ActionKey_z_Up("Key_s")
ActionKey_lalt_Up("Key_s")
HKUpPost("Key_s")
return

LabelMap5_d_down:
HKPre()
ActionKey_lalt_Down("Key_d")
ActionKey_x_Down("Key_d")
HKPost("Key_d")
return
LabelMap5_d_up:
HKUpPre()
ActionKey_x_Up("Key_d")
ActionKey_lalt_Up("Key_d")
HKUpPost("Key_d")
return

LabelMap5_f_down:
HKPre()
ActionKey_lalt_Down("Key_f")
ActionKey_c_Down("Key_f")
HKPost("Key_f")
return
LabelMap5_f_up:
HKUpPre()
ActionKey_c_Up("Key_f")
ActionKey_lalt_Up("Key_f")
HKUpPost("Key_f")
return

LabelMap5_g_down:
HKPre()
ActionKey_lalt_Down("Key_g")
ActionKey_sc029_Down("Key_g")
HKPost("Key_g")
return
LabelMap5_g_up:
HKUpPre()
ActionKey_sc029_Up("Key_g")
ActionKey_lalt_Up("Key_g")
HKUpPost("Key_g")
return

LabelMap5_t_down:
HKPre()
ActionKey_lalt_Down("Key_t")
ActionKey_v_Down("Key_t")
HKPost("Key_t")
return
LabelMap5_t_up:
HKUpPre()
ActionKey_v_Up("Key_t")
ActionKey_lalt_Up("Key_t")
HKUpPost("Key_t")
return

LabelMap5_w_down:
HKPre()
ActionKey_lalt_Down("Key_w")
ActionKey_r_Down("Key_w")
HKPost("Key_w")
return
LabelMap5_w_up:
HKUpPre()
ActionKey_r_Up("Key_w")
ActionKey_lalt_Up("Key_w")
HKUpPost("Key_w")
return

LabelMap5_r_down:
HKPre()
ActionKey_lalt_Down("Key_r")
ActionKey_f_Down("Key_r")
HKPost("Key_r")
return
LabelMap5_r_up:
HKUpPre()
ActionKey_f_Up("Key_r")
ActionKey_lalt_Up("Key_r")
HKUpPost("Key_r")
return

LabelMap5_q_down:
HKPre()
ActionKey_lalt_Down("Key_q")
ActionKey_q_Down("Key_q")
HKPost("Key_q")
return
LabelMap5_q_up:
HKUpPre()
ActionKey_q_Up("Key_q")
ActionKey_lalt_Up("Key_q")
HKUpPost("Key_q")
return

LabelMap5_3_down:
HKPre()
ActionKey_lctrl_Down("Key_3")
ActionKey_lalt_Down("Key_3")
ActionKey_e_Down("Key_3")
HKPost("Key_3")
return
LabelMap5_3_up:
HKUpPre()
ActionKey_e_Up("Key_3")
ActionKey_lctrl_Up("Key_3")
ActionKey_lalt_Up("Key_3")
HKUpPost("Key_3")
return

LabelMap6_a_down:
HKPre()
ActionKey_p_Down("Key_a")
HKPost("Key_a")
return
LabelMap6_a_up:
HKUpPre()
ActionKey_p_Up("Key_a")
HKUpPost("Key_a")
return

LabelMap6_s_down:
HKPre()
ActionKey_n_Down("Key_s")
HKPost("Key_s")
return
LabelMap6_s_up:
HKUpPre()
ActionKey_n_Up("Key_s")
HKUpPost("Key_s")
return

LabelMap6_d_down:
HKPre()
ActionKey_c_Down("Key_d")
HKPost("Key_d")
return
LabelMap6_d_up:
HKUpPre()
ActionKey_c_Up("Key_d")
HKUpPost("Key_d")
return

LabelMap6_f_down:
HKPre()
ActionKey_b_Down("Key_f")
HKPost("Key_f")
return
LabelMap6_f_up:
HKUpPre()
ActionKey_b_Up("Key_f")
HKUpPost("Key_f")
return

LabelMap6_g_down:
HKPre()
ActionKey_l_Down("Key_g")
HKPost("Key_g")
return
LabelMap6_g_up:
HKUpPre()
ActionKey_l_Up("Key_g")
HKUpPost("Key_g")
return

LabelMap6_e_down:
HKPre()
ActionKey_i_Down("Key_e")
HKPost("Key_e")
return
LabelMap6_e_up:
HKUpPre()
ActionKey_i_Up("Key_e")
HKUpPost("Key_e")
return

LabelMap6_r_down:
HKPre()
ActionKey_lctrl_Down("Key_r")
ActionKey_g_Down("Key_r")
HKPost("Key_r")
return
LabelMap6_r_up:
HKUpPre()
ActionKey_g_Up("Key_r")
ActionKey_lctrl_Up("Key_r")
HKUpPost("Key_r")
return

LabelMap6_w_down:
HKPre()
ActionKey_lshift_Down("Key_w")
ActionKey_p_Down("Key_w")
HKPost("Key_w")
return
LabelMap6_w_up:
HKUpPre()
ActionKey_p_Up("Key_w")
ActionKey_lshift_Up("Key_w")
HKUpPost("Key_w")
return

LabelMap6_c_down:
HKPre()
ActionKey_m_Down("Key_c")
HKPost("Key_c")
return
LabelMap6_c_up:
HKUpPre()
ActionKey_m_Up("Key_c")
HKUpPost("Key_c")
return

LabelMap6_v_down:
HKPre()
ActionKey_o_Down("Key_v")
HKPost("Key_v")
return
LabelMap6_v_up:
HKUpPre()
ActionKey_o_Up("Key_v")
HKUpPost("Key_v")
return

LabelMap6_b_down:
HKPre()
ActionKey_j_Down("Key_b")
HKPost("Key_b")
return
LabelMap6_b_up:
HKUpPre()
ActionKey_j_Up("Key_b")
HKUpPost("Key_b")
return

LabelMap6_x_down:
HKPre()
ActionKey_lshift_Down("Key_x")
ActionKey_j_Down("Key_x")
HKPost("Key_x")
return
LabelMap6_x_up:
HKUpPre()
ActionKey_j_Up("Key_x")
ActionKey_lshift_Up("Key_x")
HKUpPost("Key_x")
return

LabelMap6_z_down:
HKPre()
ActionKey_y_Down("Key_z")
HKPost("Key_z")
return
LabelMap6_z_up:
HKUpPre()
ActionKey_y_Up("Key_z")
HKUpPost("Key_z")
return

LabelMap7_z_down:
HKPre()
ActionKey_lalt_Down("Key_z")
ActionKey_n_Down("Key_z")
HKPost("Key_z")
return
LabelMap7_z_up:
HKUpPre()
ActionKey_n_Up("Key_z")
ActionKey_lalt_Up("Key_z")
HKUpPost("Key_z")
return

LabelMap7_x_down:
HKPre()
ActionKey_lalt_Down("Key_x")
ActionKey_m_Down("Key_x")
HKPost("Key_x")
return
LabelMap7_x_up:
HKUpPre()
ActionKey_m_Up("Key_x")
ActionKey_lalt_Up("Key_x")
HKUpPost("Key_x")
return

LabelMap7_a_down:
HKPre()
ActionKey_lalt_Down("Key_a")
ActionKey_vkdb_Down("Key_a")
HKPost("Key_a")
return
LabelMap7_a_up:
HKUpPre()
ActionKey_vkdb_Up("Key_a")
ActionKey_lalt_Up("Key_a")
HKUpPost("Key_a")
return

LabelMap7_s_down:
HKPre()
ActionKey_lalt_Down("Key_s")
ActionKey_vkdd_Down("Key_s")
HKPost("Key_s")
return
LabelMap7_s_up:
HKUpPre()
ActionKey_vkdd_Up("Key_s")
ActionKey_lalt_Up("Key_s")
HKUpPost("Key_s")
return

LabelMap7_w_down:
HKPre()
ActionKey_lctrl_Down("Key_w")
ActionKey_lalt_Down("Key_w")
ActionKey_sc029_Down("Key_w")
HKPost("Key_w")
return
LabelMap7_w_up:
HKUpPre()
ActionKey_sc029_Up("Key_w")
ActionKey_lctrl_Up("Key_w")
ActionKey_lalt_Up("Key_w")
HKUpPost("Key_w")
return

LabelMap8_f_down:
HKPre()
ActionKey_z_Down("Key_f")
HKPost("Key_f")
return
LabelMap8_f_up:
HKUpPre()
ActionKey_z_Up("Key_f")
HKUpPost("Key_f")
return

LabelMap8_d_down:
HKPre()
ActionKey_x_Down("Key_d")
HKPost("Key_d")
return
LabelMap8_d_up:
HKUpPre()
ActionKey_x_Up("Key_d")
HKUpPost("Key_d")
return

LabelMap8_z_down:
HKPre()
ActionKey_f2_Down("Key_z")
HKPost("Key_z")
return
LabelMap8_z_up:
HKUpPre()
ActionKey_f2_Up("Key_z")
HKUpPost("Key_z")
return

LabelMap8_x_down:
HKPre()
ActionKey_f3_Down("Key_x")
HKPost("Key_x")
return
LabelMap8_x_up:
HKUpPre()
ActionKey_f3_Up("Key_x")
HKUpPost("Key_x")
return

LabelMap8_c_down:
HKPre()
ActionKey_f4_Down("Key_c")
HKPost("Key_c")
return
LabelMap8_c_up:
HKUpPre()
ActionKey_f4_Up("Key_c")
HKUpPost("Key_c")
return

LabelMap8_v_down:
HKPre()
ActionKey_f5_Down("Key_v")
HKPost("Key_v")
return
LabelMap8_v_up:
HKUpPre()
ActionKey_f5_Up("Key_v")
HKUpPost("Key_v")
return

