contextSensitive := false
#Include ..\..\..\..\Engine - Keyboard.ahk
InitScript:
global maxMaps := 6
return

Label_up_down:
HKPre()
ActionKey_w_Down("Key_up")
HKPost("Key_up")
return
Label_up_up:
HKUpPre()
ActionKey_w_Up("Key_up")
HKUpPost("Key_up")
return

Label_down_down:
HKPre()
ActionKey_s_Down("Key_down")
HKPost("Key_down")
return
Label_down_up:
HKUpPre()
ActionKey_s_Up("Key_down")
HKUpPost("Key_down")
return

Label_left_down:
HKPre()
ActionKey_a_Down("Key_left")
HKPost("Key_left")
return
Label_left_up:
HKUpPre()
ActionKey_a_Up("Key_left")
HKUpPost("Key_left")
return

Label_right_down:
HKPre()
ActionKey_d_Down("Key_right")
HKPost("Key_right")
return
Label_right_up:
HKUpPre()
ActionKey_d_Up("Key_right")
HKUpPost("Key_right")
return

Label_d_down:
HKPre()
ActionKey_space_Down("Key_d")
HKPost("Key_d")
return
Label_d_up:
HKUpPre()
ActionKey_space_Up("Key_d")
HKUpPost("Key_d")
return

Label_escape_down:
HKPre()
ActionKey_escape_Down("Key_escape")
HKPost("Key_escape")
return
Label_escape_up:
HKUpPre()
ActionKey_escape_Up("Key_escape")
HKUpPost("Key_escape")
return

Label_scrolllock_down:
HKPre()
ActionKey_scrolllock_Down("Key_scrolllock")
HKPost("Key_scrolllock")
return
Label_scrolllock_up:
HKUpPre()
ActionKey_scrolllock_Up("Key_scrolllock")
HKUpPost("Key_scrolllock")
return

Label_u_down:
HKPre()
ActionKey_lctrl_Down("Key_u")
HKPost("Key_u")
return
Label_u_up:
HKUpPre()
ActionKey_lctrl_Up("Key_u")
HKUpPost("Key_u")
return

Label_j_down:
HKPre()
ActionKey_lshift_Down("Key_j")
HKPost("Key_j")
return
Label_j_up:
HKUpPre()
ActionKey_lshift_Up("Key_j")
HKUpPost("Key_j")
return

Label_m_down:
HKPre()
ActionKey_lctrl_Down("Key_m")
ActionKey_lalt_Down("Key_m")
HKPost("Key_m")
return
Label_m_up:
HKUpPre()
ActionKey_lctrl_Up("Key_m")
ActionKey_lalt_Up("Key_m")
HKUpPost("Key_m")
return

Label_w_down:
HKPre()
ActionKey_left_Down("Key_w")
HKPost("Key_w")
return
Label_w_up:
HKUpPre()
ActionKey_left_Up("Key_w")
HKUpPost("Key_w")
return

Label_r_down:
HKPre()
ActionKey_right_Down("Key_r")
HKPost("Key_r")
return
Label_r_up:
HKUpPre()
ActionKey_right_Up("Key_r")
HKUpPost("Key_r")
return

Label_z_down:
HKPre()
ActionKey_r_Down("Key_z")
HKPost("Key_z")
return
Label_z_up:
HKUpPre()
ActionKey_r_Up("Key_z")
HKUpPost("Key_z")
return

Label_o_down:
MKPre()
SwitchKeymap(3)
MKPost()
return
Label_o_up:
MKUpPre()
SwitchKeymap(1)
MKUpPost()
return

Label_8_down:
MKPre()
SwitchKeymap(4)
MKPost()
return
Label_8_up:
MKUpPre()
SwitchKeymap(1)
MKUpPost()
return

Label_i_down:
MKPre()
SwitchKeymap(5)
MKPost()
return
Label_i_up:
MKUpPre()
SwitchKeymap(1)
MKUpPost()
return

Label_k_down:
MKPre()
SwitchKeymap(6)
MKPost()
return
Label_k_up:
MKUpPre()
SwitchKeymap(1)
MKUpPost()
return

Label_3_down:
HKPre()
ActionKey_g_Down("Key_3")
HKPost("Key_3")
return
Label_3_up:
HKUpPre()
ActionKey_g_Up("Key_3")
HKUpPost("Key_3")
return

Label_a_down:
HKPre()
ActionKey_tab_Down("Key_a")
HKPost("Key_a")
return
Label_a_up:
HKUpPre()
ActionKey_tab_Up("Key_a")
HKUpPost("Key_a")
return

Label_9_down:
MKPre()
SwitchKeymap(2)
MKPost()
return
Label_9_up:
MKUpPre()
SwitchKeymap(1)
MKUpPost()
return

LabelMap2_f_down:
HKPre()
ActionKey_i_Down("Key_f")
HKPost("Key_f")
return
LabelMap2_f_up:
HKUpPre()
ActionKey_i_Up("Key_f")
HKUpPost("Key_f")
return

LabelMap2_d_down:
HKPre()
ActionKey_c_Down("Key_d")
HKPost("Key_d")
return
LabelMap2_d_up:
HKUpPre()
ActionKey_c_Up("Key_d")
HKUpPost("Key_d")
return

LabelMap2_a_down:
HKPre()
ActionKey_b_Down("Key_a")
HKPost("Key_a")
return
LabelMap2_a_up:
HKUpPre()
ActionKey_b_Up("Key_a")
HKUpPost("Key_a")
return

LabelMap2_v_down:
HKPre()
ActionKey_p_Down("Key_v")
HKPost("Key_v")
return
LabelMap2_v_up:
HKUpPre()
ActionKey_p_Up("Key_v")
HKUpPost("Key_v")
return

LabelMap2_c_down:
HKPre()
ActionKey_m_Down("Key_c")
HKPost("Key_c")
return
LabelMap2_c_up:
HKUpPre()
ActionKey_m_Up("Key_c")
HKUpPost("Key_c")
return

LabelMap2_g_down:
HKPre()
ActionKey_j_Down("Key_g")
HKPost("Key_g")
return
LabelMap2_g_up:
HKUpPre()
ActionKey_j_Up("Key_g")
HKUpPost("Key_g")
return

LabelMap2_w_down:
HKPre()
ActionKey_vkdb_Down("Key_w")
HKPost("Key_w")
return
LabelMap2_w_up:
HKUpPre()
ActionKey_vkdb_Up("Key_w")
HKUpPost("Key_w")
return

LabelMap2_r_down:
HKPre()
ActionKey_vkdd_Down("Key_r")
HKPost("Key_r")
return
LabelMap2_r_up:
HKUpPre()
ActionKey_vkdd_Up("Key_r")
HKUpPost("Key_r")
return

LabelMap3_d_down:
HKPre()
ActionKey_v_Down("Key_d")
HKPost("Key_d")
return
LabelMap3_d_up:
HKUpPre()
ActionKey_v_Up("Key_d")
HKUpPost("Key_d")
return

LabelMap3_s_down:
HKPre()
ActionKey_w_Down("Key_s")
HKPost("Key_s")
return
LabelMap3_s_up:
HKUpPre()
ActionKey_w_Up("Key_s")
HKUpPost("Key_s")
return

LabelMap3_f_down:
HKPre()
ActionKey_e_Down("Key_f")
HKPost("Key_f")
return
LabelMap3_f_up:
HKUpPre()
ActionKey_e_Up("Key_f")
HKUpPost("Key_f")
return

LabelMap4_a_down:
HKPre()
ActionKey_f1_Down("Key_a")
HKPost("Key_a")
return
LabelMap4_a_up:
HKUpPre()
ActionKey_f1_Up("Key_a")
HKUpPost("Key_a")
return

LabelMap4_s_down:
HKPre()
ActionKey_f2_Down("Key_s")
HKPost("Key_s")
return
LabelMap4_s_up:
HKUpPre()
ActionKey_f2_Up("Key_s")
HKUpPost("Key_s")
return

LabelMap4_f_down:
HKPre()
ActionKey_f3_Down("Key_f")
HKPost("Key_f")
return
LabelMap4_f_up:
HKUpPre()
ActionKey_f3_Up("Key_f")
HKUpPost("Key_f")
return

LabelMap4_g_down:
HKPre()
ActionKey_f4_Down("Key_g")
HKPost("Key_g")
return
LabelMap4_g_up:
HKUpPre()
ActionKey_f4_Up("Key_g")
HKUpPost("Key_g")
return

LabelMap4_z_down:
HKPre()
ActionKey_f5_Down("Key_z")
HKPost("Key_z")
return
LabelMap4_z_up:
HKUpPre()
ActionKey_f5_Up("Key_z")
HKUpPost("Key_z")
return

LabelMap4_x_down:
HKPre()
ActionKey_f6_Down("Key_x")
HKPost("Key_x")
return
LabelMap4_x_up:
HKUpPre()
ActionKey_f6_Up("Key_x")
HKUpPost("Key_x")
return

LabelMap4_v_down:
HKPre()
ActionKey_f7_Down("Key_v")
HKPost("Key_v")
return
LabelMap4_v_up:
HKUpPre()
ActionKey_f7_Up("Key_v")
HKUpPost("Key_v")
return

LabelMap4_b_down:
HKPre()
ActionKey_f8_Down("Key_b")
HKPost("Key_b")
return
LabelMap4_b_up:
HKUpPre()
ActionKey_f8_Up("Key_b")
HKUpPost("Key_b")
return

LabelMap4_q_down:
HKPre()
ActionKey_f9_Down("Key_q")
HKPost("Key_q")
return
LabelMap4_q_up:
HKUpPre()
ActionKey_f9_Up("Key_q")
HKUpPost("Key_q")
return

LabelMap4_w_down:
HKPre()
ActionKey_f10_Down("Key_w")
HKPost("Key_w")
return
LabelMap4_w_up:
HKUpPre()
ActionKey_f10_Up("Key_w")
HKUpPost("Key_w")
return

LabelMap4_r_down:
HKPre()
ActionKey_f11_Down("Key_r")
HKPost("Key_r")
return
LabelMap4_r_up:
HKUpPre()
ActionKey_f11_Up("Key_r")
HKUpPost("Key_r")
return

LabelMap4_t_down:
HKPre()
ActionKey_f12_Down("Key_t")
HKPost("Key_t")
return
LabelMap4_t_up:
HKUpPre()
ActionKey_f12_Up("Key_t")
HKUpPost("Key_t")
return

LabelMap5_a_down:
HKPre()
ActionKey_lctrl_Down("Key_a")
ActionKey_f1_Down("Key_a")
HKPost("Key_a")
return
LabelMap5_a_up:
HKUpPre()
ActionKey_f1_Up("Key_a")
ActionKey_lctrl_Up("Key_a")
HKUpPost("Key_a")
return

LabelMap5_s_down:
HKPre()
ActionKey_lctrl_Down("Key_s")
ActionKey_f2_Down("Key_s")
HKPost("Key_s")
return
LabelMap5_s_up:
HKUpPre()
ActionKey_f2_Up("Key_s")
ActionKey_lctrl_Up("Key_s")
HKUpPost("Key_s")
return

LabelMap5_f_down:
HKPre()
ActionKey_lctrl_Down("Key_f")
ActionKey_f3_Down("Key_f")
HKPost("Key_f")
return
LabelMap5_f_up:
HKUpPre()
ActionKey_f3_Up("Key_f")
ActionKey_lctrl_Up("Key_f")
HKUpPost("Key_f")
return

LabelMap5_g_down:
HKPre()
ActionKey_lctrl_Down("Key_g")
ActionKey_f4_Down("Key_g")
HKPost("Key_g")
return
LabelMap5_g_up:
HKUpPre()
ActionKey_f4_Up("Key_g")
ActionKey_lctrl_Up("Key_g")
HKUpPost("Key_g")
return

LabelMap5_z_down:
HKPre()
ActionKey_lctrl_Down("Key_z")
ActionKey_f5_Down("Key_z")
HKPost("Key_z")
return
LabelMap5_z_up:
HKUpPre()
ActionKey_f5_Up("Key_z")
ActionKey_lctrl_Up("Key_z")
HKUpPost("Key_z")
return

LabelMap5_x_down:
HKPre()
ActionKey_lctrl_Down("Key_x")
ActionKey_f6_Down("Key_x")
HKPost("Key_x")
return
LabelMap5_x_up:
HKUpPre()
ActionKey_f6_Up("Key_x")
ActionKey_lctrl_Up("Key_x")
HKUpPost("Key_x")
return

LabelMap5_v_down:
HKPre()
ActionKey_lctrl_Down("Key_v")
ActionKey_f7_Down("Key_v")
HKPost("Key_v")
return
LabelMap5_v_up:
HKUpPre()
ActionKey_f7_Up("Key_v")
ActionKey_lctrl_Up("Key_v")
HKUpPost("Key_v")
return

LabelMap5_b_down:
HKPre()
ActionKey_lctrl_Down("Key_b")
ActionKey_f8_Down("Key_b")
HKPost("Key_b")
return
LabelMap5_b_up:
HKUpPre()
ActionKey_f8_Up("Key_b")
ActionKey_lctrl_Up("Key_b")
HKUpPost("Key_b")
return

LabelMap5_q_down:
HKPre()
ActionKey_lctrl_Down("Key_q")
ActionKey_f9_Down("Key_q")
HKPost("Key_q")
return
LabelMap5_q_up:
HKUpPre()
ActionKey_f9_Up("Key_q")
ActionKey_lctrl_Up("Key_q")
HKUpPost("Key_q")
return

LabelMap5_w_down:
HKPre()
ActionKey_lctrl_Down("Key_w")
ActionKey_f10_Down("Key_w")
HKPost("Key_w")
return
LabelMap5_w_up:
HKUpPre()
ActionKey_f10_Up("Key_w")
ActionKey_lctrl_Up("Key_w")
HKUpPost("Key_w")
return

LabelMap5_r_down:
HKPre()
ActionKey_lctrl_Down("Key_r")
ActionKey_f11_Down("Key_r")
HKPost("Key_r")
return
LabelMap5_r_up:
HKUpPre()
ActionKey_f11_Up("Key_r")
ActionKey_lctrl_Up("Key_r")
HKUpPost("Key_r")
return

LabelMap5_t_down:
HKPre()
ActionKey_lctrl_Down("Key_t")
ActionKey_f12_Down("Key_t")
HKPost("Key_t")
return
LabelMap5_t_up:
HKUpPre()
ActionKey_f12_Up("Key_t")
ActionKey_lctrl_Up("Key_t")
HKUpPost("Key_t")
return

LabelMap6_a_down:
HKPre()
ActionKey_lshift_Down("Key_a")
ActionKey_f1_Down("Key_a")
HKPost("Key_a")
return
LabelMap6_a_up:
HKUpPre()
ActionKey_f1_Up("Key_a")
ActionKey_lshift_Up("Key_a")
HKUpPost("Key_a")
return

LabelMap6_s_down:
HKPre()
ActionKey_lshift_Down("Key_s")
ActionKey_f2_Down("Key_s")
HKPost("Key_s")
return
LabelMap6_s_up:
HKUpPre()
ActionKey_f2_Up("Key_s")
ActionKey_lshift_Up("Key_s")
HKUpPost("Key_s")
return

LabelMap6_f_down:
HKPre()
ActionKey_lshift_Down("Key_f")
ActionKey_f3_Down("Key_f")
HKPost("Key_f")
return
LabelMap6_f_up:
HKUpPre()
ActionKey_f3_Up("Key_f")
ActionKey_lshift_Up("Key_f")
HKUpPost("Key_f")
return

LabelMap6_g_down:
HKPre()
ActionKey_lshift_Down("Key_g")
ActionKey_f4_Down("Key_g")
HKPost("Key_g")
return
LabelMap6_g_up:
HKUpPre()
ActionKey_f4_Up("Key_g")
ActionKey_lshift_Up("Key_g")
HKUpPost("Key_g")
return

LabelMap6_z_down:
HKPre()
ActionKey_lshift_Down("Key_z")
ActionKey_f5_Down("Key_z")
HKPost("Key_z")
return
LabelMap6_z_up:
HKUpPre()
ActionKey_f5_Up("Key_z")
ActionKey_lshift_Up("Key_z")
HKUpPost("Key_z")
return

LabelMap6_x_down:
HKPre()
ActionKey_lshift_Down("Key_x")
ActionKey_f6_Down("Key_x")
HKPost("Key_x")
return
LabelMap6_x_up:
HKUpPre()
ActionKey_f6_Up("Key_x")
ActionKey_lshift_Up("Key_x")
HKUpPost("Key_x")
return

LabelMap6_v_down:
HKPre()
ActionKey_lshift_Down("Key_v")
ActionKey_f7_Down("Key_v")
HKPost("Key_v")
return
LabelMap6_v_up:
HKUpPre()
ActionKey_f7_Up("Key_v")
ActionKey_lshift_Up("Key_v")
HKUpPost("Key_v")
return

LabelMap6_b_down:
HKPre()
ActionKey_lshift_Down("Key_b")
ActionKey_f8_Down("Key_b")
HKPost("Key_b")
return
LabelMap6_b_up:
HKUpPre()
ActionKey_f8_Up("Key_b")
ActionKey_lshift_Up("Key_b")
HKUpPost("Key_b")
return

LabelMap6_q_down:
HKPre()
ActionKey_lshift_Down("Key_q")
ActionKey_f9_Down("Key_q")
HKPost("Key_q")
return
LabelMap6_q_up:
HKUpPre()
ActionKey_f9_Up("Key_q")
ActionKey_lshift_Up("Key_q")
HKUpPost("Key_q")
return

LabelMap6_w_down:
HKPre()
ActionKey_lshift_Down("Key_w")
ActionKey_f10_Down("Key_w")
HKPost("Key_w")
return
LabelMap6_w_up:
HKUpPre()
ActionKey_f10_Up("Key_w")
ActionKey_lshift_Up("Key_w")
HKUpPost("Key_w")
return

LabelMap6_r_down:
HKPre()
ActionKey_lshift_Down("Key_r")
ActionKey_f11_Down("Key_r")
HKPost("Key_r")
return
LabelMap6_r_up:
HKUpPre()
ActionKey_f11_Up("Key_r")
ActionKey_lshift_Up("Key_r")
HKUpPost("Key_r")
return

LabelMap6_t_down:
HKPre()
ActionKey_lshift_Down("Key_t")
ActionKey_f12_Down("Key_t")
HKPost("Key_t")
return
LabelMap6_t_up:
HKUpPre()
ActionKey_f12_Up("Key_t")
ActionKey_lshift_Up("Key_t")
HKUpPost("Key_t")
return

