contextSensitive := false
#Include ..\..\..\..\Engine - Keyboard.ahk
InitScript:
global maxMaps := 6
return

Label_h_down:
MKPre()
SwitchKeymap(6)
MKPost()
return
Label_h_up:
MKUpPre()
SwitchKeymap(1)
MKUpPost()
return

Label_escape_down:
HKPre()
ActionKey_escape_Down("Key_escape")
HKPost("Key_escape")
return
Label_escape_up:
HKUpPre()
ActionKey_escape_Up("Key_escape")
HKUpPost("Key_escape")
return

Label_scrolllock_down:
HKPre()
ActionKey_scrolllock_Down("Key_scrolllock")
HKPost("Key_scrolllock")
return
Label_scrolllock_up:
HKUpPre()
ActionKey_scrolllock_Up("Key_scrolllock")
HKUpPost("Key_scrolllock")
return

Label_left_down:
MKPre()
SwitchKeymap(2)
MKPost()
return
Label_left_up:
MKUpPre()
SwitchKeymap(1)
MKUpPost()
return

Label_up_down:
MKPre()
SwitchKeymap(3)
MKPost()
return
Label_up_up:
MKUpPre()
SwitchKeymap(1)
MKUpPost()
return

Label_right_down:
MKPre()
SwitchKeymap(4)
MKPost()
return
Label_right_up:
MKUpPre()
SwitchKeymap(1)
MKUpPost()
return

Label_down_down:
MKPre()
SwitchKeymap(5)
MKPost()
return
Label_down_up:
MKUpPre()
SwitchKeymap(1)
MKUpPost()
return

Label_4_down:
HKPre()
ActionKey_w_Down("Key_4")
HKPost("Key_4")
return
Label_4_up:
HKUpPre()
ActionKey_w_Up("Key_4")
HKUpPost("Key_4")
return

Label_r_down:
HKPre()
ActionKey_s_Down("Key_r")
HKPost("Key_r")
return
Label_r_up:
HKUpPre()
ActionKey_s_Up("Key_r")
HKUpPost("Key_r")
return

Label_e_down:
HKPre()
ActionKey_a_Down("Key_e")
HKPost("Key_e")
return
Label_e_up:
HKUpPre()
ActionKey_a_Up("Key_e")
HKUpPost("Key_e")
return

Label_t_down:
HKPre()
ActionKey_d_Down("Key_t")
HKPost("Key_t")
return
Label_t_up:
HKUpPre()
ActionKey_d_Up("Key_t")
HKUpPost("Key_t")
return

Label_q_down:
HKPre()
ActionKey_1_Down("Key_q")
HKPost("Key_q")
return
Label_q_up:
HKUpPre()
ActionKey_1_Up("Key_q")
HKUpPost("Key_q")
return

Label_w_down:
HKPre()
ActionKey_2_Down("Key_w")
HKPost("Key_w")
return
Label_w_up:
HKUpPre()
ActionKey_2_Up("Key_w")
HKUpPost("Key_w")
return

Label_y_down:
HKPre()
ActionKey_3_Down("Key_y")
HKPost("Key_y")
return
Label_y_up:
HKUpPre()
ActionKey_3_Up("Key_y")
HKUpPost("Key_y")
return

Label_u_down:
HKPre()
ActionKey_4_Down("Key_u")
HKPost("Key_u")
return
Label_u_up:
HKUpPre()
ActionKey_4_Up("Key_u")
HKUpPost("Key_u")
return

Label_1_down:
HKPre()
ActionKey_5_Down("Key_1")
HKPost("Key_1")
return
Label_1_up:
HKUpPre()
ActionKey_5_Up("Key_1")
HKUpPost("Key_1")
return

Label_2_down:
HKPre()
ActionKey_6_Down("Key_2")
HKPost("Key_2")
return
Label_2_up:
HKUpPre()
ActionKey_6_Up("Key_2")
HKUpPost("Key_2")
return

Label_3_down:
HKPre()
ActionKey_7_Down("Key_3")
HKPost("Key_3")
return
Label_3_up:
HKUpPre()
ActionKey_7_Up("Key_3")
HKUpPost("Key_3")
return

Label_5_down:
HKPre()
ActionKey_8_Down("Key_5")
HKPost("Key_5")
return
Label_5_up:
HKUpPre()
ActionKey_8_Up("Key_5")
HKUpPost("Key_5")
return

Label_6_down:
HKPre()
ActionKey_9_Down("Key_6")
HKPost("Key_6")
return
Label_6_up:
HKUpPre()
ActionKey_9_Up("Key_6")
HKUpPost("Key_6")
return

Label_7_down:
HKPre()
ActionKey_0_Down("Key_7")
HKPost("Key_7")
return
Label_7_up:
HKUpPre()
ActionKey_0_Up("Key_7")
HKUpPost("Key_7")
return

Label_a_down:
HKPre()
ActionKey_vkbd_Down("Key_a")
HKPost("Key_a")
return
Label_a_up:
HKUpPre()
ActionKey_vkbd_Up("Key_a")
HKUpPost("Key_a")
return

Label_s_down:
HKPre()
ActionKey_vkbb_Down("Key_s")
HKPost("Key_s")
return
Label_s_up:
HKUpPre()
ActionKey_vkbb_Up("Key_s")
HKUpPost("Key_s")
return

Label_f_down:
HKPre()
ActionKey_numpad0_Down("Key_f")
HKPost("Key_f")
return
Label_f_up:
HKUpPre()
ActionKey_numpad0_Up("Key_f")
HKUpPost("Key_f")
return

Label_g_down:
HKPre()
ActionKey_vkdd_Down("Key_g")
HKPost("Key_g")
return
Label_g_up:
HKUpPre()
ActionKey_vkdd_Up("Key_g")
HKUpPost("Key_g")
return

LabelMap2_q_down:
HKPre()
ActionKey_lctrl_Down("Key_q")
ActionKey_1_Down("Key_q")
HKPost("Key_q")
return
LabelMap2_q_up:
HKUpPre()
ActionKey_1_Up("Key_q")
ActionKey_lctrl_Up("Key_q")
HKUpPost("Key_q")
return

LabelMap2_w_down:
HKPre()
ActionKey_lctrl_Down("Key_w")
ActionKey_2_Down("Key_w")
HKPost("Key_w")
return
LabelMap2_w_up:
HKUpPre()
ActionKey_2_Up("Key_w")
ActionKey_lctrl_Up("Key_w")
HKUpPost("Key_w")
return

LabelMap2_y_down:
HKPre()
ActionKey_lctrl_Down("Key_y")
ActionKey_3_Down("Key_y")
HKPost("Key_y")
return
LabelMap2_y_up:
HKUpPre()
ActionKey_3_Up("Key_y")
ActionKey_lctrl_Up("Key_y")
HKUpPost("Key_y")
return

LabelMap2_u_down:
HKPre()
ActionKey_lctrl_Down("Key_u")
ActionKey_4_Down("Key_u")
HKPost("Key_u")
return
LabelMap2_u_up:
HKUpPre()
ActionKey_4_Up("Key_u")
ActionKey_lctrl_Up("Key_u")
HKUpPost("Key_u")
return

LabelMap2_1_down:
HKPre()
ActionKey_lctrl_Down("Key_1")
ActionKey_5_Down("Key_1")
HKPost("Key_1")
return
LabelMap2_1_up:
HKUpPre()
ActionKey_5_Up("Key_1")
ActionKey_lctrl_Up("Key_1")
HKUpPost("Key_1")
return

LabelMap2_2_down:
HKPre()
ActionKey_lctrl_Down("Key_2")
ActionKey_6_Down("Key_2")
HKPost("Key_2")
return
LabelMap2_2_up:
HKUpPre()
ActionKey_6_Up("Key_2")
ActionKey_lctrl_Up("Key_2")
HKUpPost("Key_2")
return

LabelMap2_3_down:
HKPre()
ActionKey_lctrl_Down("Key_3")
ActionKey_7_Down("Key_3")
HKPost("Key_3")
return
LabelMap2_3_up:
HKUpPre()
ActionKey_7_Up("Key_3")
ActionKey_lctrl_Up("Key_3")
HKUpPost("Key_3")
return

LabelMap2_5_down:
HKPre()
ActionKey_lctrl_Down("Key_5")
ActionKey_8_Down("Key_5")
HKPost("Key_5")
return
LabelMap2_5_up:
HKUpPre()
ActionKey_8_Up("Key_5")
ActionKey_lctrl_Up("Key_5")
HKUpPost("Key_5")
return

LabelMap2_6_down:
HKPre()
ActionKey_lctrl_Down("Key_6")
ActionKey_9_Down("Key_6")
HKPost("Key_6")
return
LabelMap2_6_up:
HKUpPre()
ActionKey_9_Up("Key_6")
ActionKey_lctrl_Up("Key_6")
HKUpPost("Key_6")
return

LabelMap2_7_down:
HKPre()
ActionKey_lctrl_Down("Key_7")
ActionKey_0_Down("Key_7")
HKPost("Key_7")
return
LabelMap2_7_up:
HKUpPre()
ActionKey_0_Up("Key_7")
ActionKey_lctrl_Up("Key_7")
HKUpPost("Key_7")
return

LabelMap2_a_down:
HKPre()
ActionKey_lctrl_Down("Key_a")
ActionKey_vkbd_Down("Key_a")
HKPost("Key_a")
return
LabelMap2_a_up:
HKUpPre()
ActionKey_vkbd_Up("Key_a")
ActionKey_lctrl_Up("Key_a")
HKUpPost("Key_a")
return

LabelMap2_s_down:
HKPre()
ActionKey_lctrl_Down("Key_s")
ActionKey_vkbb_Down("Key_s")
HKPost("Key_s")
return
LabelMap2_s_up:
HKUpPre()
ActionKey_vkbb_Up("Key_s")
ActionKey_lctrl_Up("Key_s")
HKUpPost("Key_s")
return

LabelMap3_r_down:
HKPre()
ActionKey_lalt_Down("Key_r")
ActionKey_e_Down("Key_r")
HKPost("Key_r")
return
LabelMap3_r_up:
HKUpPre()
ActionKey_e_Up("Key_r")
ActionKey_lalt_Up("Key_r")
HKUpPost("Key_r")
return

LabelMap3_a_down:
HKPre()
ActionKey_lalt_Down("Key_a")
ActionKey_v_Down("Key_a")
HKPost("Key_a")
return
LabelMap3_a_up:
HKUpPre()
ActionKey_v_Up("Key_a")
ActionKey_lalt_Up("Key_a")
HKUpPost("Key_a")
return

LabelMap3_w_down:
HKPre()
ActionKey_lalt_Down("Key_w")
ActionKey_z_Down("Key_w")
HKPost("Key_w")
return
LabelMap3_w_up:
HKUpPre()
ActionKey_z_Up("Key_w")
ActionKey_lalt_Up("Key_w")
HKUpPost("Key_w")
return

LabelMap3_e_down:
HKPre()
ActionKey_lalt_Down("Key_e")
ActionKey_x_Down("Key_e")
HKPost("Key_e")
return
LabelMap3_e_up:
HKUpPre()
ActionKey_x_Up("Key_e")
ActionKey_lalt_Up("Key_e")
HKUpPost("Key_e")
return

LabelMap3_t_down:
HKPre()
ActionKey_lalt_Down("Key_t")
ActionKey_c_Down("Key_t")
HKPost("Key_t")
return
LabelMap3_t_up:
HKUpPre()
ActionKey_c_Up("Key_t")
ActionKey_lalt_Up("Key_t")
HKUpPost("Key_t")
return

LabelMap3_y_down:
HKPre()
ActionKey_lalt_Down("Key_y")
ActionKey_sc029_Down("Key_y")
HKPost("Key_y")
return
LabelMap3_y_up:
HKUpPre()
ActionKey_sc029_Up("Key_y")
ActionKey_lalt_Up("Key_y")
HKUpPost("Key_y")
return

LabelMap3_7_down:
HKPre()
ActionKey_lctrl_Down("Key_7")
ActionKey_lalt_Down("Key_7")
ActionKey_e_Down("Key_7")
HKPost("Key_7")
return
LabelMap3_7_up:
HKUpPre()
ActionKey_e_Up("Key_7")
ActionKey_lctrl_Up("Key_7")
ActionKey_lalt_Up("Key_7")
HKUpPost("Key_7")
return

LabelMap3_4_down:
HKPre()
ActionKey_lalt_Down("Key_4")
ActionKey_q_Down("Key_4")
HKPost("Key_4")
return
LabelMap3_4_up:
HKUpPre()
ActionKey_q_Up("Key_4")
ActionKey_lalt_Up("Key_4")
HKUpPost("Key_4")
return

LabelMap3_3_down:
HKPre()
ActionKey_lalt_Down("Key_3")
ActionKey_r_Down("Key_3")
HKPost("Key_3")
return
LabelMap3_3_up:
HKUpPre()
ActionKey_r_Up("Key_3")
ActionKey_lalt_Up("Key_3")
HKUpPost("Key_3")
return

LabelMap3_5_down:
HKPre()
ActionKey_lalt_Down("Key_5")
ActionKey_f_Down("Key_5")
HKPost("Key_5")
return
LabelMap3_5_up:
HKUpPre()
ActionKey_f_Up("Key_5")
ActionKey_lalt_Up("Key_5")
HKUpPost("Key_5")
return

LabelMap4_q_down:
HKPre()
ActionKey_lalt_Down("Key_q")
ActionKey_1_Down("Key_q")
HKPost("Key_q")
return
LabelMap4_q_up:
HKUpPre()
ActionKey_1_Up("Key_q")
ActionKey_lalt_Up("Key_q")
HKUpPost("Key_q")
return

LabelMap4_w_down:
HKPre()
ActionKey_lalt_Down("Key_w")
ActionKey_2_Down("Key_w")
HKPost("Key_w")
return
LabelMap4_w_up:
HKUpPre()
ActionKey_2_Up("Key_w")
ActionKey_lalt_Up("Key_w")
HKUpPost("Key_w")
return

LabelMap4_y_down:
HKPre()
ActionKey_lalt_Down("Key_y")
ActionKey_3_Down("Key_y")
HKPost("Key_y")
return
LabelMap4_y_up:
HKUpPre()
ActionKey_3_Up("Key_y")
ActionKey_lalt_Up("Key_y")
HKUpPost("Key_y")
return

LabelMap4_u_down:
HKPre()
ActionKey_lalt_Down("Key_u")
ActionKey_4_Down("Key_u")
HKPost("Key_u")
return
LabelMap4_u_up:
HKUpPre()
ActionKey_4_Up("Key_u")
ActionKey_lalt_Up("Key_u")
HKUpPost("Key_u")
return

LabelMap4_1_down:
HKPre()
ActionKey_lalt_Down("Key_1")
ActionKey_5_Down("Key_1")
HKPost("Key_1")
return
LabelMap4_1_up:
HKUpPre()
ActionKey_5_Up("Key_1")
ActionKey_lalt_Up("Key_1")
HKUpPost("Key_1")
return

LabelMap4_2_down:
HKPre()
ActionKey_lalt_Down("Key_2")
ActionKey_6_Down("Key_2")
HKPost("Key_2")
return
LabelMap4_2_up:
HKUpPre()
ActionKey_6_Up("Key_2")
ActionKey_lalt_Up("Key_2")
HKUpPost("Key_2")
return

LabelMap4_3_down:
HKPre()
ActionKey_lalt_Down("Key_3")
ActionKey_7_Down("Key_3")
HKPost("Key_3")
return
LabelMap4_3_up:
HKUpPre()
ActionKey_7_Up("Key_3")
ActionKey_lalt_Up("Key_3")
HKUpPost("Key_3")
return

LabelMap4_5_down:
HKPre()
ActionKey_lalt_Down("Key_5")
ActionKey_8_Down("Key_5")
HKPost("Key_5")
return
LabelMap4_5_up:
HKUpPre()
ActionKey_8_Up("Key_5")
ActionKey_lalt_Up("Key_5")
HKUpPost("Key_5")
return

LabelMap4_6_down:
HKPre()
ActionKey_lalt_Down("Key_6")
ActionKey_9_Down("Key_6")
HKPost("Key_6")
return
LabelMap4_6_up:
HKUpPre()
ActionKey_9_Up("Key_6")
ActionKey_lalt_Up("Key_6")
HKUpPost("Key_6")
return

LabelMap4_7_down:
HKPre()
ActionKey_lalt_Down("Key_7")
ActionKey_0_Down("Key_7")
HKPost("Key_7")
return
LabelMap4_7_up:
HKUpPre()
ActionKey_0_Up("Key_7")
ActionKey_lalt_Up("Key_7")
HKUpPost("Key_7")
return

LabelMap4_a_down:
HKPre()
ActionKey_lalt_Down("Key_a")
ActionKey_vkbd_Down("Key_a")
HKPost("Key_a")
return
LabelMap4_a_up:
HKUpPre()
ActionKey_vkbd_Up("Key_a")
ActionKey_lalt_Up("Key_a")
HKUpPost("Key_a")
return

LabelMap4_s_down:
HKPre()
ActionKey_lalt_Down("Key_s")
ActionKey_vkbb_Down("Key_s")
HKPost("Key_s")
return
LabelMap4_s_up:
HKUpPre()
ActionKey_vkbb_Up("Key_s")
ActionKey_lalt_Up("Key_s")
HKUpPost("Key_s")
return

LabelMap5_q_down:
HKPre()
ActionKey_lshift_Down("Key_q")
ActionKey_1_Down("Key_q")
HKPost("Key_q")
return
LabelMap5_q_up:
HKUpPre()
ActionKey_1_Up("Key_q")
ActionKey_lshift_Up("Key_q")
HKUpPost("Key_q")
return

LabelMap5_w_down:
HKPre()
ActionKey_lshift_Down("Key_w")
ActionKey_2_Down("Key_w")
HKPost("Key_w")
return
LabelMap5_w_up:
HKUpPre()
ActionKey_2_Up("Key_w")
ActionKey_lshift_Up("Key_w")
HKUpPost("Key_w")
return

LabelMap5_y_down:
HKPre()
ActionKey_lshift_Down("Key_y")
ActionKey_3_Down("Key_y")
HKPost("Key_y")
return
LabelMap5_y_up:
HKUpPre()
ActionKey_3_Up("Key_y")
ActionKey_lshift_Up("Key_y")
HKUpPost("Key_y")
return

LabelMap5_u_down:
HKPre()
ActionKey_lshift_Down("Key_u")
ActionKey_4_Down("Key_u")
HKPost("Key_u")
return
LabelMap5_u_up:
HKUpPre()
ActionKey_4_Up("Key_u")
ActionKey_lshift_Up("Key_u")
HKUpPost("Key_u")
return

LabelMap5_1_down:
HKPre()
ActionKey_lshift_Down("Key_1")
ActionKey_5_Down("Key_1")
HKPost("Key_1")
return
LabelMap5_1_up:
HKUpPre()
ActionKey_5_Up("Key_1")
ActionKey_lshift_Up("Key_1")
HKUpPost("Key_1")
return

LabelMap5_2_down:
HKPre()
ActionKey_lshift_Down("Key_2")
ActionKey_6_Down("Key_2")
HKPost("Key_2")
return
LabelMap5_2_up:
HKUpPre()
ActionKey_6_Up("Key_2")
ActionKey_lshift_Up("Key_2")
HKUpPost("Key_2")
return

LabelMap5_3_down:
HKPre()
ActionKey_lshift_Down("Key_3")
ActionKey_7_Down("Key_3")
HKPost("Key_3")
return
LabelMap5_3_up:
HKUpPre()
ActionKey_7_Up("Key_3")
ActionKey_lshift_Up("Key_3")
HKUpPost("Key_3")
return

LabelMap5_5_down:
HKPre()
ActionKey_lshift_Down("Key_5")
ActionKey_8_Down("Key_5")
HKPost("Key_5")
return
LabelMap5_5_up:
HKUpPre()
ActionKey_8_Up("Key_5")
ActionKey_lshift_Up("Key_5")
HKUpPost("Key_5")
return

LabelMap5_6_down:
HKPre()
ActionKey_lshift_Down("Key_6")
ActionKey_9_Down("Key_6")
HKPost("Key_6")
return
LabelMap5_6_up:
HKUpPre()
ActionKey_9_Up("Key_6")
ActionKey_lshift_Up("Key_6")
HKUpPost("Key_6")
return

LabelMap5_7_down:
HKPre()
ActionKey_lshift_Down("Key_7")
ActionKey_0_Down("Key_7")
HKPost("Key_7")
return
LabelMap5_7_up:
HKUpPre()
ActionKey_0_Up("Key_7")
ActionKey_lshift_Up("Key_7")
HKUpPost("Key_7")
return

LabelMap5_a_down:
HKPre()
ActionKey_lshift_Down("Key_a")
ActionKey_vkbd_Down("Key_a")
HKPost("Key_a")
return
LabelMap5_a_up:
HKUpPre()
ActionKey_vkbd_Up("Key_a")
ActionKey_lshift_Up("Key_a")
HKUpPost("Key_a")
return

LabelMap5_s_down:
HKPre()
ActionKey_lshift_Down("Key_s")
ActionKey_vkbb_Down("Key_s")
HKPost("Key_s")
return
LabelMap5_s_up:
HKUpPre()
ActionKey_vkbb_Up("Key_s")
ActionKey_lshift_Up("Key_s")
HKUpPost("Key_s")
return

LabelMap5_d_down:
HKPre()
ActionKey_tab_Down("Key_d")
HKPost("Key_d")
return
LabelMap5_d_up:
HKUpPre()
ActionKey_tab_Up("Key_d")
HKUpPost("Key_d")
return

LabelMap5_f_down:
HKPre()
ActionKey_f_Down("Key_f")
HKPost("Key_f")
return
LabelMap5_f_up:
HKUpPre()
ActionKey_f_Up("Key_f")
HKUpPost("Key_f")
return

LabelMap5_g_down:
HKPre()
ActionKey_t_Down("Key_g")
HKPost("Key_g")
return
LabelMap5_g_up:
HKUpPre()
ActionKey_t_Up("Key_g")
HKUpPost("Key_g")
return

LabelMap6_r_down:
HKPre()
ActionKey_c_Down("Key_r")
HKPost("Key_r")
return
LabelMap6_r_up:
HKUpPre()
ActionKey_c_Up("Key_r")
HKUpPost("Key_r")
return

LabelMap6_t_down:
HKPre()
ActionKey_b_Down("Key_t")
HKPost("Key_t")
return
LabelMap6_t_up:
HKUpPre()
ActionKey_b_Up("Key_t")
HKUpPost("Key_t")
return

LabelMap6_y_down:
HKPre()
ActionKey_l_Down("Key_y")
HKPost("Key_y")
return
LabelMap6_y_up:
HKUpPre()
ActionKey_l_Up("Key_y")
HKUpPost("Key_y")
return

LabelMap6_e_down:
HKPre()
ActionKey_n_Down("Key_e")
HKPost("Key_e")
return
LabelMap6_e_up:
HKUpPre()
ActionKey_n_Up("Key_e")
HKUpPost("Key_e")
return

LabelMap6_w_down:
HKPre()
ActionKey_p_Down("Key_w")
HKPost("Key_w")
return
LabelMap6_w_up:
HKUpPre()
ActionKey_p_Up("Key_w")
HKUpPost("Key_w")
return

LabelMap6_d_down:
HKPre()
ActionKey_m_Down("Key_d")
HKPost("Key_d")
return
LabelMap6_d_up:
HKUpPre()
ActionKey_m_Up("Key_d")
HKUpPost("Key_d")
return

LabelMap6_f_down:
HKPre()
ActionKey_j_Down("Key_f")
HKPost("Key_f")
return
LabelMap6_f_up:
HKUpPre()
ActionKey_j_Up("Key_f")
HKUpPost("Key_f")
return

LabelMap6_g_down:
HKPre()
ActionKey_o_Down("Key_g")
HKPost("Key_g")
return
LabelMap6_g_up:
HKUpPre()
ActionKey_o_Up("Key_g")
HKUpPost("Key_g")
return

LabelMap6_s_down:
HKPre()
ActionKey_lshift_Down("Key_s")
ActionKey_j_Down("Key_s")
HKPost("Key_s")
return
LabelMap6_s_up:
HKUpPre()
ActionKey_j_Up("Key_s")
ActionKey_lshift_Up("Key_s")
HKUpPost("Key_s")
return

LabelMap6_a_down:
HKPre()
ActionKey_y_Down("Key_a")
HKPost("Key_a")
return
LabelMap6_a_up:
HKUpPre()
ActionKey_y_Up("Key_a")
HKUpPost("Key_a")
return

LabelMap6_5_down:
HKPre()
ActionKey_lctrl_Down("Key_5")
ActionKey_g_Down("Key_5")
HKPost("Key_5")
return
LabelMap6_5_up:
HKUpPre()
ActionKey_g_Up("Key_5")
ActionKey_lctrl_Up("Key_5")
HKUpPost("Key_5")
return

LabelMap6_3_down:
HKPre()
ActionKey_lshift_Down("Key_3")
ActionKey_p_Down("Key_3")
HKPost("Key_3")
return
LabelMap6_3_up:
HKUpPre()
ActionKey_p_Up("Key_3")
ActionKey_lshift_Up("Key_3")
HKUpPost("Key_3")
return

