contextSensitive := false
#Include ..\..\..\..\Engine - Keyboard.ahk
InitScript:
global maxMaps := 8
return

Label_up_down:
HKPre()
ActionKey_w_Down("Key_up")
HKPost("Key_up")
return
Label_up_up:
HKUpPre()
ActionKey_w_Up("Key_up")
HKUpPost("Key_up")
return

Label_down_down:
HKPre()
ActionKey_s_Down("Key_down")
HKPost("Key_down")
return
Label_down_up:
HKUpPre()
ActionKey_s_Up("Key_down")
HKUpPost("Key_down")
return

Label_left_down:
HKPre()
ActionKey_a_Down("Key_left")
HKPost("Key_left")
return
Label_left_up:
HKUpPre()
ActionKey_a_Up("Key_left")
HKUpPost("Key_left")
return

Label_right_down:
HKPre()
ActionKey_d_Down("Key_right")
HKPost("Key_right")
return
Label_right_up:
HKUpPre()
ActionKey_d_Up("Key_right")
HKUpPost("Key_right")
return

Label_r_down:
HKPre()
ActionKey_space_Down("Key_r")
HKPost("Key_r")
return
Label_r_up:
HKUpPre()
ActionKey_space_Up("Key_r")
HKUpPost("Key_r")
return

Label_w_down:
HKPre()
ActionKey_1_Down("Key_w")
HKPost("Key_w")
return
Label_w_up:
HKUpPre()
ActionKey_1_Up("Key_w")
HKUpPost("Key_w")
return

Label_e_down:
HKPre()
ActionKey_2_Down("Key_e")
HKPost("Key_e")
return
Label_e_up:
HKUpPre()
ActionKey_2_Up("Key_e")
HKUpPost("Key_e")
return

Label_t_down:
HKPre()
ActionKey_3_Down("Key_t")
HKPost("Key_t")
return
Label_t_up:
HKUpPre()
ActionKey_3_Up("Key_t")
HKUpPost("Key_t")
return

Label_y_down:
HKPre()
ActionKey_4_Down("Key_y")
HKPost("Key_y")
return
Label_y_up:
HKUpPre()
ActionKey_4_Up("Key_y")
HKUpPost("Key_y")
return

Label_a_down:
HKPre()
ActionKey_5_Down("Key_a")
HKPost("Key_a")
return
Label_a_up:
HKUpPre()
ActionKey_5_Up("Key_a")
HKUpPost("Key_a")
return

Label_s_down:
HKPre()
ActionKey_6_Down("Key_s")
HKPost("Key_s")
return
Label_s_up:
HKUpPre()
ActionKey_6_Up("Key_s")
HKUpPost("Key_s")
return

Label_f_down:
HKPre()
ActionKey_7_Down("Key_f")
HKPost("Key_f")
return
Label_f_up:
HKUpPre()
ActionKey_7_Up("Key_f")
HKUpPost("Key_f")
return

Label_g_down:
HKPre()
ActionKey_8_Down("Key_g")
HKPost("Key_g")
return
Label_g_up:
HKUpPre()
ActionKey_8_Up("Key_g")
HKUpPost("Key_g")
return

Label_2_down:
HKPre()
ActionKey_9_Down("Key_2")
HKPost("Key_2")
return
Label_2_up:
HKUpPre()
ActionKey_9_Up("Key_2")
HKUpPost("Key_2")
return

Label_3_down:
HKPre()
ActionKey_0_Down("Key_3")
HKPost("Key_3")
return
Label_3_up:
HKUpPre()
ActionKey_0_Up("Key_3")
HKUpPost("Key_3")
return

Label_5_down:
HKPre()
ActionKey_-_Down("Key_5")
HKPost("Key_5")
return
Label_5_up:
HKUpPre()
ActionKey_-_Up("Key_5")
HKUpPost("Key_5")
return

Label_6_down:
HKPre()
ActionKey_=_Down("Key_6")
HKPost("Key_6")
return
Label_6_up:
HKUpPre()
ActionKey_=_Up("Key_6")
HKUpPost("Key_6")
return

Label_d_down:
HKPre()
ActionKey_numpad0_Down("Key_d")
HKPost("Key_d")
return
Label_d_up:
HKUpPre()
ActionKey_numpad0_Up("Key_d")
HKUpPost("Key_d")
return

Label_m_down:
MKPre()
SwitchKeymap(3)
MKPost()
return
Label_m_up:
MKUpPre()
SwitchKeymap(1)
MKUpPost()
return

Label_8_down:
MKPre()
SwitchKeymap(2)
MKPost()
return
Label_8_up:
MKUpPre()
SwitchKeymap(1)
MKUpPost()
return

Label_i_down:
MKPre()
SwitchKeymap(4)
MKPost()
return
Label_i_up:
MKUpPre()
SwitchKeymap(1)
MKUpPost()
return

Label_9_down:
MKPre()
SwitchKeymap(5)
MKPost()
return
Label_9_up:
MKUpPre()
SwitchKeymap(1)
MKUpPost()
return

Label_o_down:
MKPre()
SwitchKeymap(6)
MKPost()
return
Label_o_up:
MKUpPre()
SwitchKeymap(1)
MKUpPost()
return

Label_0_down:
MKPre()
SwitchKeymap(7)
MKPost()
return
Label_0_up:
MKUpPre()
SwitchKeymap(1)
MKUpPost()
return

Label_p_down:
MKPre()
SwitchKeymap(8)
MKPost()
return
Label_p_up:
MKUpPre()
SwitchKeymap(1)
MKUpPost()
return

Label_z_down:
HKPre()
ActionKey_lctrl_Down("Key_z")
HKPost("Key_z")
return
Label_z_up:
HKUpPre()
ActionKey_lctrl_Up("Key_z")
HKUpPost("Key_z")
return

Label_x_down:
HKPre()
ActionKey_lalt_Down("Key_x")
HKPost("Key_x")
return
Label_x_up:
HKUpPre()
ActionKey_lalt_Up("Key_x")
HKUpPost("Key_x")
return

Label_c_down:
HKPre()
ActionKey_lshift_Down("Key_c")
HKPost("Key_c")
return
Label_c_up:
HKUpPre()
ActionKey_lshift_Up("Key_c")
HKUpPost("Key_c")
return

Label_q_down:
HKPre()
ActionKey_sc029_Down("Key_q")
HKPost("Key_q")
return
Label_q_up:
HKUpPre()
ActionKey_sc029_Up("Key_q")
HKUpPost("Key_q")
return

Label_scrolllock_down:
HKPre()
ActionKey_scrolllock_Down("Key_scrolllock")
HKPost("Key_scrolllock")
return
Label_scrolllock_up:
HKUpPre()
ActionKey_scrolllock_Up("Key_scrolllock")
HKUpPost("Key_scrolllock")
return

Label_escape_down:
HKPre()
ActionKey_escape_Down("Key_escape")
HKPost("Key_escape")
return
Label_escape_up:
HKUpPre()
ActionKey_escape_Up("Key_escape")
HKUpPost("Key_escape")
return

Label_4_down:
HKPre()
ActionKey_vkdd_Down("Key_4")
HKPost("Key_4")
return
Label_4_up:
HKUpPre()
ActionKey_vkdd_Up("Key_4")
HKUpPost("Key_4")
return

LabelMap2_w_down:
HKPre()
ActionKey_lctrl_Down("Key_w")
ActionKey_1_Down("Key_w")
HKPost("Key_w")
return
LabelMap2_w_up:
HKUpPre()
ActionKey_1_Up("Key_w")
ActionKey_lctrl_Up("Key_w")
HKUpPost("Key_w")
return

LabelMap2_e_down:
HKPre()
ActionKey_lctrl_Down("Key_e")
ActionKey_2_Down("Key_e")
HKPost("Key_e")
return
LabelMap2_e_up:
HKUpPre()
ActionKey_2_Up("Key_e")
ActionKey_lctrl_Up("Key_e")
HKUpPost("Key_e")
return

LabelMap2_t_down:
HKPre()
ActionKey_lctrl_Down("Key_t")
ActionKey_3_Down("Key_t")
HKPost("Key_t")
return
LabelMap2_t_up:
HKUpPre()
ActionKey_3_Up("Key_t")
ActionKey_lctrl_Up("Key_t")
HKUpPost("Key_t")
return

LabelMap2_y_down:
HKPre()
ActionKey_lctrl_Down("Key_y")
ActionKey_4_Down("Key_y")
HKPost("Key_y")
return
LabelMap2_y_up:
HKUpPre()
ActionKey_4_Up("Key_y")
ActionKey_lctrl_Up("Key_y")
HKUpPost("Key_y")
return

LabelMap2_a_down:
HKPre()
ActionKey_lctrl_Down("Key_a")
ActionKey_5_Down("Key_a")
HKPost("Key_a")
return
LabelMap2_a_up:
HKUpPre()
ActionKey_5_Up("Key_a")
ActionKey_lctrl_Up("Key_a")
HKUpPost("Key_a")
return

LabelMap2_s_down:
HKPre()
ActionKey_lctrl_Down("Key_s")
ActionKey_6_Down("Key_s")
HKPost("Key_s")
return
LabelMap2_s_up:
HKUpPre()
ActionKey_6_Up("Key_s")
ActionKey_lctrl_Up("Key_s")
HKUpPost("Key_s")
return

LabelMap2_f_down:
HKPre()
ActionKey_lctrl_Down("Key_f")
ActionKey_7_Down("Key_f")
HKPost("Key_f")
return
LabelMap2_f_up:
HKUpPre()
ActionKey_7_Up("Key_f")
ActionKey_lctrl_Up("Key_f")
HKUpPost("Key_f")
return

LabelMap2_g_down:
HKPre()
ActionKey_lctrl_Down("Key_g")
ActionKey_8_Down("Key_g")
HKPost("Key_g")
return
LabelMap2_g_up:
HKUpPre()
ActionKey_8_Up("Key_g")
ActionKey_lctrl_Up("Key_g")
HKUpPost("Key_g")
return

LabelMap2_2_down:
HKPre()
ActionKey_lctrl_Down("Key_2")
ActionKey_9_Down("Key_2")
HKPost("Key_2")
return
LabelMap2_2_up:
HKUpPre()
ActionKey_9_Up("Key_2")
ActionKey_lctrl_Up("Key_2")
HKUpPost("Key_2")
return

LabelMap2_3_down:
HKPre()
ActionKey_lctrl_Down("Key_3")
ActionKey_0_Down("Key_3")
HKPost("Key_3")
return
LabelMap2_3_up:
HKUpPre()
ActionKey_0_Up("Key_3")
ActionKey_lctrl_Up("Key_3")
HKUpPost("Key_3")
return

LabelMap2_5_down:
HKPre()
ActionKey_lctrl_Down("Key_5")
ActionKey_-_Down("Key_5")
HKPost("Key_5")
return
LabelMap2_5_up:
HKUpPre()
ActionKey_-_Up("Key_5")
ActionKey_lctrl_Up("Key_5")
HKUpPost("Key_5")
return

LabelMap2_6_down:
HKPre()
ActionKey_lctrl_Down("Key_6")
ActionKey_=_Down("Key_6")
HKPost("Key_6")
return
LabelMap2_6_up:
HKUpPre()
ActionKey_=_Up("Key_6")
ActionKey_lctrl_Up("Key_6")
HKUpPost("Key_6")
return

LabelMap3_w_down:
HKPre()
ActionKey_lshift_Down("Key_w")
ActionKey_1_Down("Key_w")
HKPost("Key_w")
return
LabelMap3_w_up:
HKUpPre()
ActionKey_1_Up("Key_w")
ActionKey_lshift_Up("Key_w")
HKUpPost("Key_w")
return

LabelMap3_e_down:
HKPre()
ActionKey_lshift_Down("Key_e")
ActionKey_2_Down("Key_e")
HKPost("Key_e")
return
LabelMap3_e_up:
HKUpPre()
ActionKey_2_Up("Key_e")
ActionKey_lshift_Up("Key_e")
HKUpPost("Key_e")
return

LabelMap3_t_down:
HKPre()
ActionKey_lshift_Down("Key_t")
ActionKey_3_Down("Key_t")
HKPost("Key_t")
return
LabelMap3_t_up:
HKUpPre()
ActionKey_3_Up("Key_t")
ActionKey_lshift_Up("Key_t")
HKUpPost("Key_t")
return

LabelMap3_y_down:
HKPre()
ActionKey_lshift_Down("Key_y")
ActionKey_4_Down("Key_y")
HKPost("Key_y")
return
LabelMap3_y_up:
HKUpPre()
ActionKey_4_Up("Key_y")
ActionKey_lshift_Up("Key_y")
HKUpPost("Key_y")
return

LabelMap3_a_down:
HKPre()
ActionKey_lshift_Down("Key_a")
ActionKey_5_Down("Key_a")
HKPost("Key_a")
return
LabelMap3_a_up:
HKUpPre()
ActionKey_5_Up("Key_a")
ActionKey_lshift_Up("Key_a")
HKUpPost("Key_a")
return

LabelMap3_s_down:
HKPre()
ActionKey_lshift_Down("Key_s")
ActionKey_6_Down("Key_s")
HKPost("Key_s")
return
LabelMap3_s_up:
HKUpPre()
ActionKey_6_Up("Key_s")
ActionKey_lshift_Up("Key_s")
HKUpPost("Key_s")
return

LabelMap3_f_down:
HKPre()
ActionKey_lshift_Down("Key_f")
ActionKey_7_Down("Key_f")
HKPost("Key_f")
return
LabelMap3_f_up:
HKUpPre()
ActionKey_7_Up("Key_f")
ActionKey_lshift_Up("Key_f")
HKUpPost("Key_f")
return

LabelMap3_g_down:
HKPre()
ActionKey_lshift_Down("Key_g")
ActionKey_8_Down("Key_g")
HKPost("Key_g")
return
LabelMap3_g_up:
HKUpPre()
ActionKey_8_Up("Key_g")
ActionKey_lshift_Up("Key_g")
HKUpPost("Key_g")
return

LabelMap3_2_down:
HKPre()
ActionKey_lshift_Down("Key_2")
ActionKey_9_Down("Key_2")
HKPost("Key_2")
return
LabelMap3_2_up:
HKUpPre()
ActionKey_9_Up("Key_2")
ActionKey_lshift_Up("Key_2")
HKUpPost("Key_2")
return

LabelMap3_3_down:
HKPre()
ActionKey_lshift_Down("Key_3")
ActionKey_0_Down("Key_3")
HKPost("Key_3")
return
LabelMap3_3_up:
HKUpPre()
ActionKey_0_Up("Key_3")
ActionKey_lshift_Up("Key_3")
HKUpPost("Key_3")
return

LabelMap3_5_down:
HKPre()
ActionKey_lshift_Down("Key_5")
ActionKey_-_Down("Key_5")
HKPost("Key_5")
return
LabelMap3_5_up:
HKUpPre()
ActionKey_-_Up("Key_5")
ActionKey_lshift_Up("Key_5")
HKUpPost("Key_5")
return

LabelMap3_6_down:
HKPre()
ActionKey_lshift_Down("Key_6")
ActionKey_=_Down("Key_6")
HKPost("Key_6")
return
LabelMap3_6_up:
HKUpPre()
ActionKey_=_Up("Key_6")
ActionKey_lshift_Up("Key_6")
HKUpPost("Key_6")
return

LabelMap3_4_down:
HKPre()
ActionKey_lalt_Down("Key_4")
ActionKey_e_Down("Key_4")
HKPost("Key_4")
return
LabelMap3_4_up:
HKUpPre()
ActionKey_e_Up("Key_4")
ActionKey_lalt_Up("Key_4")
HKUpPost("Key_4")
return

LabelMap3_q_down:
HKPre()
ActionKey_tab_Down("Key_q")
HKPost("Key_q")
return
LabelMap3_q_up:
HKUpPre()
ActionKey_tab_Up("Key_q")
HKUpPost("Key_q")
return

LabelMap3_7_down:
HKPre()
ActionKey_f_Down("Key_7")
HKPost("Key_7")
return
LabelMap3_7_up:
HKUpPre()
ActionKey_f_Up("Key_7")
HKUpPost("Key_7")
return

LabelMap3_u_down:
HKPre()
ActionKey_t_Down("Key_u")
HKPost("Key_u")
return
LabelMap3_u_up:
HKUpPre()
ActionKey_t_Up("Key_u")
HKUpPost("Key_u")
return

LabelMap4_w_down:
HKPre()
ActionKey_lalt_Down("Key_w")
ActionKey_1_Down("Key_w")
HKPost("Key_w")
return
LabelMap4_w_up:
HKUpPre()
ActionKey_1_Up("Key_w")
ActionKey_lalt_Up("Key_w")
HKUpPost("Key_w")
return

LabelMap4_e_down:
HKPre()
ActionKey_lalt_Down("Key_e")
ActionKey_2_Down("Key_e")
HKPost("Key_e")
return
LabelMap4_e_up:
HKUpPre()
ActionKey_2_Up("Key_e")
ActionKey_lalt_Up("Key_e")
HKUpPost("Key_e")
return

LabelMap4_t_down:
HKPre()
ActionKey_lalt_Down("Key_t")
ActionKey_3_Down("Key_t")
HKPost("Key_t")
return
LabelMap4_t_up:
HKUpPre()
ActionKey_3_Up("Key_t")
ActionKey_lalt_Up("Key_t")
HKUpPost("Key_t")
return

LabelMap4_y_down:
HKPre()
ActionKey_lalt_Down("Key_y")
ActionKey_4_Down("Key_y")
HKPost("Key_y")
return
LabelMap4_y_up:
HKUpPre()
ActionKey_4_Up("Key_y")
ActionKey_lalt_Up("Key_y")
HKUpPost("Key_y")
return

LabelMap4_a_down:
HKPre()
ActionKey_lalt_Down("Key_a")
ActionKey_5_Down("Key_a")
HKPost("Key_a")
return
LabelMap4_a_up:
HKUpPre()
ActionKey_5_Up("Key_a")
ActionKey_lalt_Up("Key_a")
HKUpPost("Key_a")
return

LabelMap4_s_down:
HKPre()
ActionKey_lalt_Down("Key_s")
ActionKey_6_Down("Key_s")
HKPost("Key_s")
return
LabelMap4_s_up:
HKUpPre()
ActionKey_6_Up("Key_s")
ActionKey_lalt_Up("Key_s")
HKUpPost("Key_s")
return

LabelMap4_f_down:
HKPre()
ActionKey_lalt_Down("Key_f")
ActionKey_7_Down("Key_f")
HKPost("Key_f")
return
LabelMap4_f_up:
HKUpPre()
ActionKey_7_Up("Key_f")
ActionKey_lalt_Up("Key_f")
HKUpPost("Key_f")
return

LabelMap4_g_down:
HKPre()
ActionKey_lalt_Down("Key_g")
ActionKey_8_Down("Key_g")
HKPost("Key_g")
return
LabelMap4_g_up:
HKUpPre()
ActionKey_8_Up("Key_g")
ActionKey_lalt_Up("Key_g")
HKUpPost("Key_g")
return

LabelMap4_2_down:
HKPre()
ActionKey_lalt_Down("Key_2")
ActionKey_9_Down("Key_2")
HKPost("Key_2")
return
LabelMap4_2_up:
HKUpPre()
ActionKey_9_Up("Key_2")
ActionKey_lalt_Up("Key_2")
HKUpPost("Key_2")
return

LabelMap4_3_down:
HKPre()
ActionKey_lalt_Down("Key_3")
ActionKey_0_Down("Key_3")
HKPost("Key_3")
return
LabelMap4_3_up:
HKUpPre()
ActionKey_0_Up("Key_3")
ActionKey_lalt_Up("Key_3")
HKUpPost("Key_3")
return

LabelMap4_5_down:
HKPre()
ActionKey_lalt_Down("Key_5")
ActionKey_-_Down("Key_5")
HKPost("Key_5")
return
LabelMap4_5_up:
HKUpPre()
ActionKey_-_Up("Key_5")
ActionKey_lalt_Up("Key_5")
HKUpPost("Key_5")
return

LabelMap4_6_down:
HKPre()
ActionKey_lalt_Down("Key_6")
ActionKey_=_Down("Key_6")
HKPost("Key_6")
return
LabelMap4_6_up:
HKUpPre()
ActionKey_=_Up("Key_6")
ActionKey_lalt_Up("Key_6")
HKUpPost("Key_6")
return

LabelMap5_r_down:
HKPre()
ActionKey_c_Down("Key_r")
HKPost("Key_r")
return
LabelMap5_r_up:
HKUpPre()
ActionKey_c_Up("Key_r")
HKUpPost("Key_r")
return

LabelMap5_t_down:
HKPre()
ActionKey_b_Down("Key_t")
HKPost("Key_t")
return
LabelMap5_t_up:
HKUpPre()
ActionKey_b_Up("Key_t")
HKUpPost("Key_t")
return

LabelMap5_e_down:
HKPre()
ActionKey_n_Down("Key_e")
HKPost("Key_e")
return
LabelMap5_e_up:
HKUpPre()
ActionKey_n_Up("Key_e")
HKUpPost("Key_e")
return

LabelMap5_w_down:
HKPre()
ActionKey_p_Down("Key_w")
HKPost("Key_w")
return
LabelMap5_w_up:
HKUpPre()
ActionKey_p_Up("Key_w")
HKUpPost("Key_w")
return

LabelMap5_y_down:
HKPre()
ActionKey_l_Down("Key_y")
HKPost("Key_y")
return
LabelMap5_y_up:
HKUpPre()
ActionKey_l_Up("Key_y")
HKUpPost("Key_y")
return

LabelMap5_d_down:
HKPre()
ActionKey_m_Down("Key_d")
HKPost("Key_d")
return
LabelMap5_d_up:
HKUpPre()
ActionKey_m_Up("Key_d")
HKUpPost("Key_d")
return

LabelMap5_f_down:
HKPre()
ActionKey_o_Down("Key_f")
HKPost("Key_f")
return
LabelMap5_f_up:
HKUpPre()
ActionKey_o_Up("Key_f")
HKUpPost("Key_f")
return

LabelMap5_g_down:
HKPre()
ActionKey_j_Down("Key_g")
HKPost("Key_g")
return
LabelMap5_g_up:
HKUpPre()
ActionKey_j_Up("Key_g")
HKUpPost("Key_g")
return

LabelMap5_a_down:
HKPre()
ActionKey_y_Down("Key_a")
HKPost("Key_a")
return
LabelMap5_a_up:
HKUpPre()
ActionKey_y_Up("Key_a")
HKUpPost("Key_a")
return

LabelMap5_s_down:
HKPre()
ActionKey_lshift_Down("Key_s")
ActionKey_j_Down("Key_s")
HKPost("Key_s")
return
LabelMap5_s_up:
HKUpPre()
ActionKey_j_Up("Key_s")
ActionKey_lshift_Up("Key_s")
HKUpPost("Key_s")
return

LabelMap5_5_down:
HKPre()
ActionKey_lctrl_Down("Key_5")
ActionKey_g_Down("Key_5")
HKPost("Key_5")
return
LabelMap5_5_up:
HKUpPre()
ActionKey_g_Up("Key_5")
ActionKey_lctrl_Up("Key_5")
HKUpPost("Key_5")
return

LabelMap5_4_down:
HKPre()
ActionKey_i_Down("Key_4")
HKPost("Key_4")
return
LabelMap5_4_up:
HKUpPre()
ActionKey_i_Up("Key_4")
HKUpPost("Key_4")
return

LabelMap5_3_down:
HKPre()
ActionKey_lshift_Down("Key_3")
ActionKey_p_Down("Key_3")
HKPost("Key_3")
return
LabelMap5_3_up:
HKUpPre()
ActionKey_p_Up("Key_3")
ActionKey_lshift_Up("Key_3")
HKUpPost("Key_3")
return

LabelMap6_e_down:
HKPre()
ActionKey_lalt_Down("Key_e")
ActionKey_e_Down("Key_e")
HKPost("Key_e")
return
LabelMap6_e_up:
HKUpPre()
ActionKey_e_Up("Key_e")
ActionKey_lalt_Up("Key_e")
HKUpPost("Key_e")
return

LabelMap6_t_down:
HKPre()
ActionKey_lalt_Down("Key_t")
ActionKey_x_Down("Key_t")
HKPost("Key_t")
return
LabelMap6_t_up:
HKUpPre()
ActionKey_x_Up("Key_t")
ActionKey_lalt_Up("Key_t")
HKUpPost("Key_t")
return

LabelMap6_y_down:
HKPre()
ActionKey_lalt_Down("Key_y")
ActionKey_c_Down("Key_y")
HKPost("Key_y")
return
LabelMap6_y_up:
HKUpPre()
ActionKey_c_Up("Key_y")
ActionKey_lalt_Up("Key_y")
HKUpPost("Key_y")
return

LabelMap6_w_down:
HKPre()
ActionKey_lalt_Down("Key_w")
ActionKey_z_Down("Key_w")
HKPost("Key_w")
return
LabelMap6_w_up:
HKUpPre()
ActionKey_z_Up("Key_w")
ActionKey_lalt_Up("Key_w")
HKUpPost("Key_w")
return

LabelMap6_4_down:
HKPre()
ActionKey_lalt_Down("Key_4")
ActionKey_q_Down("Key_4")
HKPost("Key_4")
return
LabelMap6_4_up:
HKUpPre()
ActionKey_q_Up("Key_4")
ActionKey_lalt_Up("Key_4")
HKUpPost("Key_4")
return

LabelMap6_a_down:
HKPre()
ActionKey_lalt_Down("Key_a")
ActionKey_sc029_Down("Key_a")
HKPost("Key_a")
return
LabelMap6_a_up:
HKUpPre()
ActionKey_sc029_Up("Key_a")
ActionKey_lalt_Up("Key_a")
HKUpPost("Key_a")
return

LabelMap6_5_down:
HKPre()
ActionKey_lalt_Down("Key_5")
ActionKey_f_Down("Key_5")
HKPost("Key_5")
return
LabelMap6_5_up:
HKUpPre()
ActionKey_f_Up("Key_5")
ActionKey_lalt_Up("Key_5")
HKUpPost("Key_5")
return

LabelMap6_3_down:
HKPre()
ActionKey_lalt_Down("Key_3")
ActionKey_r_Down("Key_3")
HKPost("Key_3")
return
LabelMap6_3_up:
HKUpPre()
ActionKey_r_Up("Key_3")
ActionKey_lalt_Up("Key_3")
HKUpPost("Key_3")
return

LabelMap6_q_down:
HKPre()
ActionKey_lalt_Down("Key_q")
ActionKey_v_Down("Key_q")
HKPost("Key_q")
return
LabelMap6_q_up:
HKUpPre()
ActionKey_v_Up("Key_q")
ActionKey_lalt_Up("Key_q")
HKUpPost("Key_q")
return

LabelMap6_6_down:
HKPre()
ActionKey_lctrl_Down("Key_6")
ActionKey_lalt_Down("Key_6")
ActionKey_e_Down("Key_6")
HKPost("Key_6")
return
LabelMap6_6_up:
HKUpPre()
ActionKey_e_Up("Key_6")
ActionKey_lctrl_Up("Key_6")
ActionKey_lalt_Up("Key_6")
HKUpPost("Key_6")
return

LabelMap7_a_down:
HKPre()
ActionKey_lctrl_Down("Key_a")
ActionKey_lalt_Down("Key_a")
ActionKey_sc029_Down("Key_a")
HKPost("Key_a")
return
LabelMap7_a_up:
HKUpPre()
ActionKey_sc029_Up("Key_a")
ActionKey_lctrl_Up("Key_a")
ActionKey_lalt_Up("Key_a")
HKUpPost("Key_a")
return

LabelMap7_e_down:
HKPre()
ActionKey_lalt_Down("Key_e")
ActionKey_n_Down("Key_e")
HKPost("Key_e")
return
LabelMap7_e_up:
HKUpPre()
ActionKey_n_Up("Key_e")
ActionKey_lalt_Up("Key_e")
HKUpPost("Key_e")
return

LabelMap7_t_down:
HKPre()
ActionKey_lalt_Down("Key_t")
ActionKey_m_Down("Key_t")
HKPost("Key_t")
return
LabelMap7_t_up:
HKUpPre()
ActionKey_m_Up("Key_t")
ActionKey_lalt_Up("Key_t")
HKUpPost("Key_t")
return

LabelMap7_3_down:
HKPre()
ActionKey_lalt_Down("Key_3")
ActionKey_[_Down("Key_3")
HKPost("Key_3")
return
LabelMap7_3_up:
HKUpPre()
ActionKey_[_Up("Key_3")
ActionKey_lalt_Up("Key_3")
HKUpPost("Key_3")
return

LabelMap7_5_down:
HKPre()
ActionKey_lalt_Down("Key_5")
ActionKey_]_Down("Key_5")
HKPost("Key_5")
return
LabelMap7_5_up:
HKUpPre()
ActionKey_]_Up("Key_5")
ActionKey_lalt_Up("Key_5")
HKUpPost("Key_5")
return

LabelMap8_e_down:
HKPre()
ActionKey_x_Down("Key_e")
HKPost("Key_e")
return
LabelMap8_e_up:
HKUpPre()
ActionKey_x_Up("Key_e")
HKUpPost("Key_e")
return

LabelMap8_t_down:
HKPre()
ActionKey_z_Down("Key_t")
HKPost("Key_t")
return
LabelMap8_t_up:
HKUpPre()
ActionKey_z_Up("Key_t")
HKUpPost("Key_t")
return

LabelMap8_w_down:
HKPre()
ActionKey_numpaddiv_Down("Key_w")
HKPost("Key_w")
return
LabelMap8_w_up:
HKUpPre()
ActionKey_numpaddiv_Up("Key_w")
HKUpPost("Key_w")
return

LabelMap8_a_down:
HKPre()
ActionKey_f2_Down("Key_a")
HKPost("Key_a")
return
LabelMap8_a_up:
HKUpPre()
ActionKey_f2_Up("Key_a")
HKUpPost("Key_a")
return

LabelMap8_s_down:
HKPre()
ActionKey_f3_Down("Key_s")
HKPost("Key_s")
return
LabelMap8_s_up:
HKUpPre()
ActionKey_f3_Up("Key_s")
HKUpPost("Key_s")
return

LabelMap8_f_down:
HKPre()
ActionKey_f4_Down("Key_f")
HKPost("Key_f")
return
LabelMap8_f_up:
HKUpPre()
ActionKey_f4_Up("Key_f")
HKUpPost("Key_f")
return

LabelMap8_g_down:
HKPre()
ActionKey_f5_Down("Key_g")
HKPost("Key_g")
return
LabelMap8_g_up:
HKUpPre()
ActionKey_f5_Up("Key_g")
HKUpPost("Key_g")
return

