contextSensitive := false
#Include ..\..\..\..\Engine - Keyboard.ahk
InitScript:
global maxMaps := 3
return

Label_e_down:
HKPre()
ActionKey_up_Down("Key_e")
HKPost("Key_e")
return
Label_e_up:
HKUpPre()
ActionKey_up_Up("Key_e")
HKUpPost("Key_e")
return

Label_d_down:
HKPre()
ActionKey_down_Down("Key_d")
HKPost("Key_d")
return
Label_d_up:
HKUpPre()
ActionKey_down_Up("Key_d")
HKUpPost("Key_d")
return

Label_s_down:
HKPre()
ActionKey_left_Down("Key_s")
HKPost("Key_s")
return
Label_s_up:
HKUpPre()
ActionKey_left_Up("Key_s")
HKUpPost("Key_s")
return

Label_f_down:
HKPre()
ActionKey_right_Down("Key_f")
HKPost("Key_f")
return
Label_f_up:
HKUpPre()
ActionKey_right_Up("Key_f")
HKUpPost("Key_f")
return

Label_w_down:
HKPre()
ActionKey_vkbc_Down("Key_w")
HKPost("Key_w")
return
Label_w_up:
HKUpPre()
ActionKey_vkbc_Up("Key_w")
HKUpPost("Key_w")
return

Label_r_down:
HKPre()
ActionKey_vkbe_Down("Key_r")
HKPost("Key_r")
return
Label_r_up:
HKUpPre()
ActionKey_vkbe_Up("Key_r")
HKUpPost("Key_r")
return

Label_lshift_down:
HKPre()
ActionKey_lshift_Down("Key_lshift")
HKPost("Key_lshift")
return
Label_lshift_up:
HKUpPre()
ActionKey_lshift_Up("Key_lshift")
HKUpPost("Key_lshift")
return

Label_lctrl_down:
HKPre()
ActionKey_lctrl_Down("Key_lctrl")
HKPost("Key_lctrl")
return
Label_lctrl_up:
HKUpPre()
ActionKey_lctrl_Up("Key_lctrl")
HKUpPost("Key_lctrl")
return

Label_f13_down:
HKPre()
ActionKey_f13_Down("Key_f13")
HKPost("Key_f13")
return
Label_f13_up:
HKUpPre()
ActionKey_f13_Up("Key_f13")
HKUpPost("Key_f13")
return

Label_sc029_down:
HKPre()
ActionKey_sc029_Down("Key_sc029")
HKPost("Key_sc029")
return
Label_sc029_up:
HKUpPre()
ActionKey_sc029_Up("Key_sc029")
HKUpPost("Key_sc029")
return

Label_1_down:
HKPre()
ActionKey_1_Down("Key_1")
HKPost("Key_1")
return
Label_1_up:
HKUpPre()
ActionKey_1_Up("Key_1")
HKUpPost("Key_1")
return

Label_2_down:
HKPre()
ActionKey_2_Down("Key_2")
HKPost("Key_2")
return
Label_2_up:
HKUpPre()
ActionKey_2_Up("Key_2")
HKUpPost("Key_2")
return

Label_3_down:
HKPre()
ActionKey_3_Down("Key_3")
HKPost("Key_3")
return
Label_3_up:
HKUpPre()
ActionKey_3_Up("Key_3")
HKUpPost("Key_3")
return

Label_4_down:
HKPre()
ActionKey_4_Down("Key_4")
HKPost("Key_4")
return
Label_4_up:
HKUpPre()
ActionKey_4_Up("Key_4")
HKUpPost("Key_4")
return

Label_a_down:
MKPre()
SwitchKeymap(2)
MKPost()
return
Label_a_up:
MKUpPre()
SwitchKeymap(1)
MKUpPost()
return

Label_x_down:
HKPre()
ActionKey_delete_Down("Key_x")
HKPost("Key_x")
return
Label_x_up:
HKUpPre()
ActionKey_delete_Up("Key_x")
HKUpPost("Key_x")
return

Label_space_down:
HKPre()
ActionKey_space_Down("Key_space")
HKPost("Key_space")
return
Label_space_up:
HKUpPre()
ActionKey_space_Up("Key_space")
HKUpPost("Key_space")
return

Label_5_down:
HKPre()
ActionKey_enter_Down("Key_5")
HKPost("Key_5")
return
Label_5_up:
HKUpPre()
ActionKey_enter_Up("Key_5")
HKUpPost("Key_5")
return

Label_q_down:
MKPre()
SwitchKeymap(3)
MKPost()
return
Label_q_up:
MKUpPre()
SwitchKeymap(1)
MKUpPost()
return

Label_g_down:
HKPre()
ActionKey_m_Down("Key_g")
HKPost("Key_g")
return
Label_g_up:
HKUpPre()
ActionKey_m_Up("Key_g")
HKUpPost("Key_g")
return

Label_t_down:
HKPre()
ActionKey_lshift_Down("Key_t")
ActionKey_enter_Down("Key_t")
HKPost("Key_t")
return
Label_t_up:
HKUpPre()
ActionKey_enter_Up("Key_t")
ActionKey_lshift_Up("Key_t")
HKUpPost("Key_t")
return

Label_lalt_down:
HKPre()
ActionKey_lalt_Down("Key_lalt")
HKPost("Key_lalt")
return
Label_lalt_up:
HKUpPre()
ActionKey_lalt_Up("Key_lalt")
HKUpPost("Key_lalt")
return

Label_escape_down:
HKPre()
ActionKey_escape_Down("Key_escape")
HKPost("Key_escape")
return
Label_escape_up:
HKUpPre()
ActionKey_escape_Up("Key_escape")
HKUpPost("Key_escape")
return

Label_scrolllock_down:
HKPre()
ActionKey_scrolllock_Down("Key_scrolllock")
HKPost("Key_scrolllock")
return
Label_scrolllock_up:
HKUpPre()
ActionKey_scrolllock_Up("Key_scrolllock")
HKUpPost("Key_scrolllock")
return

LabelMap2_x_down:
HKPre()
ActionKey_lctrl_Down("Key_x")
ActionKey_z_Down("Key_x")
HKPost("Key_x")
return
LabelMap2_x_up:
HKUpPre()
ActionKey_z_Up("Key_x")
ActionKey_lctrl_Up("Key_x")
HKUpPost("Key_x")
return

LabelMap2_c_down:
HKPre()
ActionKey_lctrl_Down("Key_c")
ActionKey_y_Down("Key_c")
HKPost("Key_c")
return
LabelMap2_c_up:
HKUpPre()
ActionKey_y_Up("Key_c")
ActionKey_lctrl_Up("Key_c")
HKUpPost("Key_c")
return

LabelMap2_w_down:
HKPre()
ActionKey_e_Down("Key_w")
HKPost("Key_w")
return
LabelMap2_w_up:
HKUpPre()
ActionKey_e_Up("Key_w")
HKUpPost("Key_w")
return

LabelMap2_r_down:
HKPre()
ActionKey_h_Down("Key_r")
HKPost("Key_r")
return
LabelMap2_r_up:
HKUpPre()
ActionKey_h_Up("Key_r")
HKUpPost("Key_r")
return

LabelMap2_g_down:
HKPre()
ActionKey_k_Down("Key_g")
HKPost("Key_g")
return
LabelMap2_g_up:
HKUpPre()
ActionKey_k_Up("Key_g")
HKUpPost("Key_g")
return

LabelMap2_t_down:
HKPre()
ActionKey_r_Down("Key_t")
HKPost("Key_t")
return
LabelMap2_t_up:
HKUpPre()
ActionKey_r_Up("Key_t")
HKUpPost("Key_t")
return

LabelMap3_r_down:
HKPre()
ActionKey_pgup_Down("Key_r")
HKPost("Key_r")
return
LabelMap3_r_up:
HKUpPre()
ActionKey_pgup_Up("Key_r")
HKUpPost("Key_r")
return

LabelMap3_f_down:
HKPre()
ActionKey_pgdn_Down("Key_f")
HKPost("Key_f")
return
LabelMap3_f_up:
HKUpPre()
ActionKey_pgdn_Up("Key_f")
HKUpPost("Key_f")
return

LabelMap3_w_down:
HKPre()
ActionKey_home_Down("Key_w")
HKPost("Key_w")
return
LabelMap3_w_up:
HKUpPre()
ActionKey_home_Up("Key_w")
HKUpPost("Key_w")
return

LabelMap3_s_down:
HKPre()
ActionKey_end_Down("Key_s")
HKPost("Key_s")
return
LabelMap3_s_up:
HKUpPre()
ActionKey_end_Up("Key_s")
HKUpPost("Key_s")
return

LabelMap3_2_down:
HKPre()
ActionKey_f1_Down("Key_2")
HKPost("Key_2")
return
LabelMap3_2_up:
HKUpPre()
ActionKey_f1_Up("Key_2")
HKUpPost("Key_2")
return

LabelMap3_3_down:
HKPre()
ActionKey_f2_Down("Key_3")
HKPost("Key_3")
return
LabelMap3_3_up:
HKUpPre()
ActionKey_f2_Up("Key_3")
HKUpPost("Key_3")
return

LabelMap3_4_down:
HKPre()
ActionKey_f3_Down("Key_4")
HKPost("Key_4")
return
LabelMap3_4_up:
HKUpPre()
ActionKey_f3_Up("Key_4")
HKUpPost("Key_4")
return

